[FE] feat: 리뷰 상품 요약 컴포넌트 구현
woowacourse-teams/2023-fun-eat pull request #113
Opened 2023-07-22 10:24 UTC by hae-on

## Issue

- close #110

## ✨ 구현한 기능

- 리뷰 상품 요약 컴포넌트를 구현하였습니다.

이야기 나눈대로 ProductRankingItem을 variant를 나누어 스타일 수정을 하였습니다.
이름도 바꾸었습니다. 전체 상품의 이미지랑 상품명만 보여주기 때문에 'ProductOverviewItem'으로 수정하였습니다.
리뷰 상품에 보여지는 부분을 default로 명명하고, 랭킹에 사용하는 부분을 'ranking'으로 정하였습니다.

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

## 📸 사진

<img width="1089" alt="스크린샷 2023-07-22 오후 7 22 42" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/80464961/11772a9a-5f4b-4118-86a7-f4256e4284d8">

## ⏰ 일정

- 추정 시간 : 3시간
- 걸린 시간 : 1시간

2023-07-22 10:38 UTC, xodms0309 requested changes
빠르시군요 해옹..

2023-07-22 10:38 UTC, xodms0309 commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
> +const ProductOverviewContainer = styled.div<{ variant: 'default' | 'ranking' }>`
`ProductRankingItemProps`에서 Pick 해올 수 있을 것 같아요! 그리고 저 인터페이스 네이밍도 변경되어야 할 것 같습니다

2023-07-22 10:51 UTC, Leejin-Yang reviewed
해온 수고했어요!
빠르게 리팩터링 했네요 역시
코멘트 확인해주세요 😊

2023-07-22 10:51 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.stories.tsx
> +import ProductOverviewItem from './ProductOverviewItem';
이름 좋네요 👍

2023-07-22 10:51 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductRankingList/ProductRankingList.tsx
> +import ProductRankingItem from '../ProductOverviewItem/ProductOverviewItem';
컴포넌트 이름 수정해주세요!

2023-07-22 10:51 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
> +  productRanking: ProductRanking;
```suggestion
  rank?: number;
  name: string;
  image: string;
```

아직 상품 랭킹 관련 API가 없어서 감이 오지 않지만 랭킹이 있을수도 없을 수도로 표현할 수 있을거 같아요. 그러면 현재 variant도 rank 유무로 판단할 수 있으니 아래 스타일도 rank 유무로 판단하는건 어떤가요?

2023-07-22 10:51 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductRankingList/ProductRankingList.tsx
> +          <ProductRankingItem productRanking={productRanking} variant="ranking" />
```suggestion
          <ProductOverviewItem rank={productRanking.rank} name={productRanking.name} image={productRanking.image} />
```

그렇다면 여기는 이런식으로 될 수 있겠네요. rank값은 API가 어떻게 올지 모르지만 index를 활용할 수 있겠네요.

랭킹이 없는 상품 요약의 경우는 
```
<ProductOverviewItem name={productRanking.name} image={productRanking.image} />
```
요런 느낌일거에요.

2023-07-22 10:51 UTC, Leejin-Yang commented on frontend/src/components/Product/index.ts
> +export { default as ProductOverviewItem } from './ProductOverviewItem/ProductOverviewItem';
🌞👍

2023-07-22 12:43 UTC, hae-on commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
> +  productRanking: ProductRanking;
좋습니다 그렇게 하면 따로 variant를 나눌 필요가 없어지네요! 한번 말씀하신대로 수정해봤는데 확인해주세요~~

2023-07-22 13:17 UTC, Leejin-Yang approved these changes
해온 완벽합니다 👍
코멘트 하나 남겼는데 이것만 확인해주세요
수고했어요 🌞

2023-07-22 13:17 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
> +      <ProductOverviewImage src={image} alt={`${rank}위 상품`} />
이미지 alt 속성도 바뀌겠네용

2023-07-23 02:59 UTC, hae-on commented on frontend/src/components/Product/ProductOverviewItem/ProductOverviewItem.tsx
> +      <ProductOverviewImage src={image} alt={`${rank}위 상품`} />
예리하시군요 수정 완!

2023-07-25 00:50 UTC, merged