[BE] feat: 카카오 로그인 기능을 추가
woowacourse-teams/2023-fun-eat pull request #123
Opened 2023-07-24 14:00 UTC by 70825

## Issue

- close #68

## ✨ 구현한 기능

- 카카오 로그인을 하면 HttpSession을 통해 세션에 저장하고, 클라이언트에게 세션 ID를 반환하도록 만들었습니다.
- 테스트 코드 및 기존 코드 수정은 이야기 후에 추가할 예정

## 📢 논의하고 싶은 내용

- [x] [ALL] Redirect URI 필요
- [x] [ALL] 카카오 API를 통해 어떻게 정보를 가져오는지
- [x] [ALL] 멤버 필드 추가 및 다른 필드 제거
  - [추가] platformId (카카오 회원 번호)
  - [삭제] age, gender, phoneNumber
- [x] [BE] Session vs JWT
- [x] [BE] 환경변수 이야기 필요

## 🎸 기타

### RestTemplate vs WebClient
- 스프링 5.0 이후부터는 WebClient를 권고 ([링크](https://tecoble.techcourse.co.kr/post/2021-07-25-resttemplate-webclient/))
- WebClient는 Spring WebFlux 의존성 추가가 필요
- 성능적으로 보면 RestTemplate는 동기/블로킹 처리, WebClient가 비동기/논블로킹 처리라 WebClient가 좋아보임
- 하지만 WebFlux는 동시 사용자가 1,000명 이상이어야 유의미한 성능 향상이 있으므로 RestTemplate을 사용해도 문제 없음 ([링크](https://dzone.com/articles/raw-performance-numbers-spring-boot-2-webflux-vs-s) - 링크에서 boot 1은 Spring MVC, boot 2는 Spring WebFlux 입니다)

## ⏰ 일정

- 추정 시간 : 12
- 걸린 시간 : 5일

2023-07-24 14:21 UTC, 70825 commented on backend/build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
[jjwt에서 의존성을 3개 추가하라고 나와 있습니다](https://github.com/jwtk/jjwt#install-jdk-gradle)

2023-07-24 14:21 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/service/AuthService.java
> +            final String phoneNumber = "010-1234-1234";
- age : 현재 가져올 수 없습니다
- gender : 선택 동의를 한 경우에만 가져올 수 있습니다
- phoneNumber : 현재 가져올 수 없습니다

2023-07-24 14:21 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
> +        this.restTemplate = restTemplateBuilder.build();
RestTemplate는 빈으로 등록되어 있지 않지만, RestTemplateBuilder가 빈으로 등록되어 있어서 이걸 사용했습니다.

2023-07-24 14:21 UTC, 70825 commented on backend/src/main/java/com/funeat/member/domain/Member.java
> +    private String platformId;
카카오 회원 번호입니다

2023-07-24 14:43 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/service/AuthService.java
> +    private Member findOrCreateMember(final UserInfoDto userInfoDto) {
여기는 `@Transactional`을 붙여야 하는데 private 메서드라 못 붙인 상황이에요 🧐
바로 위에 loginWithKakao에 붙이는건 좀 아닌 것 같아서 추천점해주세요

2023-07-26 03:33 UTC, 70825 reviewed
1. 인터셉터 만들기 (역할 : 올바른 세션 ID가 아닐 때 예외 처리 용도)
2. 로그인이 필요한 곳에 interceptor 경로 등록 (ex. 좋아요, 리뷰 작성, ...)
3. 로그인이 필요한 모든 인수 테스트에 테스트 추가하기 (로그인 실패)
현재 만들어진 곳은 test에서 확인 가능함

2023-07-27 04:38 UTC, Go-Jaecheol requested changes
어려운 기능 구현하느라 고생했어요 🥲
몇 가지 작은 수정 사항들이랑 코멘트 남겼습니다!

2023-07-27 04:38 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/auth/application/AuthService.java
> +public class AuthService {
```suggestion
@Service
@Transactional(readOnly = true)
public class AuthService {
```

2023-07-27 04:38 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/member/persistence/MemberRepository.java
> +    Optional<Member> findByPlatformId(String platformId);
```suggestion
    Optional<Member> findByPlatformId(final String platformId);
```

2023-07-27 04:38 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/auth/presentation/AuthController.java
> +        return ResponseEntity.ok().build();
프론트랑 얘기해보고
`로그인하는 경우`, `회원가입하는 경우`로 나눠서 
각각 다른 페이지로 redirect 하도록 나중에 수정해야 될 것 같아요!

2023-07-27 04:38 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/acceptance/common/TestPlatformUserProvider.java
> +    public UserInfoDto getPlatformUser(String code) {
```suggestion
    public UserInfoDto getPlatformUser(final String code) {
```

2023-07-27 04:42 UTC, 70825 commented on backend/src/main/java/com/funeat/member/persistence/MemberRepository.java
> +    Optional<Member> findByPlatformId(String platformId);
생각해보니 Repository 테스트를 추가 안했네요

2023-07-27 04:49 UTC, hanueleee requested changes
너무 멋져요 로건..👍

2023-07-27 04:49 UTC, hanueleee commented on backend/src/main/java/com/funeat/auth/application/AuthService.java
> +        return member.getId();
실제 db속 member의 id보다는 sessionId용으로 뭔가 가공해서 넘기는건 어떨까요..!

2023-07-27 05:13 UTC, 70825 reviewed
```
Hibernate: 
    select
        member0_.id as id1_1_,
        member0_.nickname as nickname2_1_,
        member0_.platform_id as platform3_1_,
        member0_.profile_image as profile_4_1_ 
    from
        member member0_
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([id1_1_] : [BIGINT]) - [1]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([nickname2_1_] : [VARCHAR]) - [test1]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([platform3_1_] : [VARCHAR]) - [null]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([profile_4_1_] : [VARCHAR]) - [test1.png]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([id1_1_] : [BIGINT]) - [2]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([nickname2_1_] : [VARCHAR]) - [test2]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([platform3_1_] : [VARCHAR]) - [null]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([profile_4_1_] : [VARCHAR]) - [test2.png]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([id1_1_] : [BIGINT]) - [3]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([nickname2_1_] : [VARCHAR]) - [test3]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([platform3_1_] : [VARCHAR]) - [null]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([profile_4_1_] : [VARCHAR]) - [test3.png]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([id1_1_] : [BIGINT]) - [4]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([nickname2_1_] : [VARCHAR]) - [test4]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([platform3_1_] : [VARCHAR]) - [null]
2023-07-27 14:07:53.726 TRACE 23622 --- [    Test worker] o.h.type.descriptor.sql.BasicExtractor   : extracted value ([profile_4_1_] : [VARCHAR]) - [test4.png]
```
MemberServiceTest의 코드에 없는 데이터가 계속 추가되어서 어디서 테스트 격리가 안된 것 같아요. 근데 전부 코드상으로는 격리가 되어 있는 것처럼 보여서 모르겠네요

======

#155

2023-07-27 05:17 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/application/AuthService.java
> +        return member.getId();
member id를 그대로 반환하는건 보안쪽으로 위험할 수 있으니 JWT처럼 암호화 알고리즘 같은걸 사용해서 넘기는걸 말하는 걸까요??

2023-07-27 07:21 UTC, hanueleee commented on backend/src/main/java/com/funeat/auth/application/AuthService.java
> +        return member.getId();
```java
    @GetMapping("/login/oauth2/code/kakao")
    public ResponseEntity<Void> kakaoLogin(@RequestParam("code") final String code,
                                           final HttpServletRequest request) {
        final Long memberId = authService.loginWithKakao(code);
        request.getSession().setAttribute("member", memberId);
        return ResponseEntity.ok().build();
   }
```
아 요기서 memberId를 그대로 session에 저장하길래 memberId가 그대로 sessionId가 되는줄 알았는데,
spring에서 자동으로 뭔가의 작업을 거쳐(?) sessionId로 만들어주나보네요..!
memberId가 그대로 노출되는게 아니어서 지금도 괜찮을 것 같습니다!! 👍

2023-07-27 08:44 UTC, 70825 reviewed
1. Service Test PR merge 후에 merge 하기
2. 회의에서 이야기 했던 것처럼 리다이렉트하기

2023-07-28 06:46 UTC, 70825 commented on backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java
> +    }
<img width="400" alt="스크린샷 2023-07-28 오후 3 40 52" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/79046106/597464c9-7647-4c77-9c9f-40e3c8999d15">

카카오 로그인을 하려면 이렇게 이메일과 비밀번호를 입력해야 하는데, 여기서 나오는 인가 코드가 1회용 코드라서 테스트가 불가능해요.
왜냐하면 테스트 수행할 때, 자동적으로 이메일과 비밀번호를 입력해서 인가 코드를 받아야 하는데, 알잘딱깔센하게 이메일과 비밀번호를 입력하게 만드는 방법이 없어보입니다.
그래서 `authService.loginWithKakao(code)`는 RestAssured로 테스트가 불가능하므로 MockMvc를 사용하여 테스트를 진행했습니다.

2023-07-28 06:50 UTC, 70825 commented on backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java
> +}
<img width="400" alt="스크린샷 2023-07-28 오후 3 40 52" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/79046106/597464c9-7647-4c77-9c9f-40e3c8999d15">

카카오 로그인을 하려면 이렇게 이메일과 비밀번호를 입력해야 하는데, 여기서 나오는 인가 코드가 1회용 코드라서 테스트가 불가능해요.
왜냐하면 테스트 수행할 때, 자동적으로 이메일과 비밀번호를 입력해서 인가 코드를 받아야 하는데, 알잘딱깔센하게 이메일과 비밀번호를 입력하게 만드는 방법이 없어보입니다.
그래서 `authService.loginWithKakao(code)`는 RestAssured로 테스트가 불가능하므로 MockMvc를 사용하여 테스트를 진행했습니다.

2023-07-28 07:07 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/application/MemberService.java
> +                .map(value -> SignUserDto.of(false, value))
```value``` 보다 조금 더 명시적인 member 는 어떠신가요?

2023-07-28 07:08 UTC, wugawuga approved these changes
로그인이 로거인이 됐네요 정말 수고 많으셨어요!!! 🙇‍♂️

2023-07-28 07:09 UTC, hanueleee approved these changes
소셜 로그인 테스트.. 멋져요..👍

2023-07-28 07:10 UTC, Go-Jaecheol approved these changes
로그인.. 확실히 복잡하네요..
고생하셨습니다~!

2023-07-28 07:10 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/auth/presentation/AuthControllerTest.java
> +}
이런 이유라면 테스트 작성 안하는 것보다는 MockMvc로 테스트 하는 게 맞다고 생각합니다! 굿굿

2023-07-28 07:11 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/util/KakaoPlatformUserProvider.java
> +    }
우가 피드백이 확실히 더 좋은 코드 같아요~!

2023-07-28 08:26 UTC, 70825 commented
세션은 `세션 ID - 세션 객체`로 이루어져 있습니다.

`org.apache.catalina.session`의 `ManagerBase` 클래스에서 `protected Map<String,Session> sessions = new ConcurrentHashMap<>();`에서 쿠키에 저장된 ID를 통해 세션을 가져옵니다.

세션을 가져올 때에는 `findSession(Stirng id)`를 통해 `JSESSIONID`에 맞는 세션을 가져오는 것 같아요.
```java
    @Override
    public Session findSession(String id) throws IOException {
        if (id == null) {
            return null;
        }
        return sessions.get(id);
    }
```

이제 실제로 세션을 가져오는 것은 확인하는 것은 `org.apache.catalina.connector.Request`에서 확인할 수 있습니다.

```java
    public Session getSessionInternal() {
        return doGetSession(true);
    }
```

```java
    protected Session doGetSession(boolean create) {

        // There cannot be a session if no context has been assigned yet
        Context context = getContext();
        if (context == null) {
            return null;
        }

        // Return the current session if it exists and is valid
        if ((session != null) && !session.isValid()) {
            session = null;
        }
        if (session != null) {
            return session;
        }

        // Return the requested session if it exists and is valid
        Manager manager = context.getManager();
        if (manager == null) {
            return null; // Sessions are not supported
        }
        if (requestedSessionId != null) {
            try {
                session = manager.findSession(requestedSessionId);
            } catch (IOException e) {
                if (log.isDebugEnabled()) {
                    log.debug(sm.getString("request.session.failed", requestedSessionId, e.getMessage()), e);
                } else {
                    log.info(sm.getString("request.session.failed", requestedSessionId, e.getMessage()));
                }
                session = null;
            }
            if ((session != null) && !session.isValid()) {
                session = null;
            }
            if (session != null) {
                session.access();
                return session;
            }
        }

        // Create a new session if requested and the response is not committed
        if (!create) {
            return null;
        }
        boolean trackModesIncludesCookie =
                context.getServletContext().getEffectiveSessionTrackingModes().contains(SessionTrackingMode.COOKIE);
        if (trackModesIncludesCookie && response.getResponse().isCommitted()) {
            throw new IllegalStateException(sm.getString("coyoteRequest.sessionCreateCommitted"));
        }

        // Re-use session IDs provided by the client in very limited
        // circumstances.
        String sessionId = getRequestedSessionId();
        if (requestedSessionSSL) {
            // If the session ID has been obtained from the SSL handshake then
            // use it.
        } else if (("/".equals(context.getSessionCookiePath()) && isRequestedSessionIdFromCookie())) {
            /*
             * This is the common(ish) use case: using the same session ID with multiple web applications on the same
             * host. Typically this is used by Portlet implementations. It only works if sessions are tracked via
             * cookies. The cookie must have a path of "/" else it won't be provided for requests to all web
             * applications.
             *
             * Any session ID provided by the client should be for a session that already exists somewhere on the host.
             * Check if the context is configured for this to be confirmed.
             */
            if (context.getValidateClientProvidedNewSessionId()) {
                boolean found = false;
                for (Container container : getHost().findChildren()) {
                    Manager m = ((Context) container).getManager();
                    if (m != null) {
                        try {
                            if (m.findSession(sessionId) != null) {
                                found = true;
                                break;
                            }
                        } catch (IOException e) {
                            // Ignore. Problems with this manager will be
                            // handled elsewhere.
                        }
                    }
                }
                if (!found) {
                    sessionId = null;
                }
            }
        } else {
            sessionId = null;
        }
        session = manager.createSession(sessionId);

        // Creating a new session cookie based on that session
        if (session != null && trackModesIncludesCookie) {
            Cookie cookie =
                    ApplicationSessionCookieConfig.createSessionCookie(context, session.getIdInternal(), isSecure());

            response.addSessionCookieInternal(cookie);
        }

        if (session == null) {
            return null;
        }

        session.access();
        return session;
    }
```

이쪽에서 `session = manager.findSession(requestedSessionId);`를 통해 세션을 가져오고, 그러면 아래에 조건문에서 `!= null`로 인해 `return session`을 반환합니다.

try - catch문을 벗어나면 이제 새로운 세션을 생성하는 일이에요.

그래서 클라이언트가 쿠키에 저장된 JSESSIONID을 헤더로 보내면 JSESSIONID를 통해 Session 객체를 찾고, Session 객체에 있는 name을 통해 value를 확인하는 과정이 됩니다.

2023-07-28 09:02 UTC, merged