[BE] feat : 카테고리별 상품 목록 조회시 정렬 조건 추가 (평점순 / 리뷰개수순)
woowacourse-teams/2023-fun-eat pull request #146
Opened 2023-07-26 07:08 UTC by hanueleee

## Issue

- close #134 

## ✨ 구현한 기능

카테고리별 상품 목록 조회 조건에 `평점순`과 `리뷰개수순` 추가

- 오전에 논의했던 대로 `@formula`사용 대신 조회에 사용되는 repository 메서드 분리 
  - findAllByCategory : 평점순/가격순
  - findAllByCategoryOrderByReviewCountDesc : 리뷰개수순
- findAll~의 반환값을 Page<Product>에서 Page<ProductInCategoryDto>로 수정

## 📢 논의하고 싶은 내용

- ProductAcceptanceTest에서 테스트의 중심이 아닌 Review 데이터 세팅할 때
  - reviewRepository.save(new Review~);
  - restAssured로 review 작성 api 요청

## 🎸 기타

-  X

## ⏰ 일정

- 추정 시간 : 2h
- 걸린 시간 : 6h

2023-07-26 07:38 UTC, 70825 requested changes
오잉 고생했어요~!
수정할 부분 리뷰 남겼는데 확인하고 반영해줄 수 있나요??

2023-07-26 07:38 UTC, 70825 commented on backend/src/main/java/com/funeat/product/domain/Product.java
> +                   final Category category) {
```suggestion
                   final Double averageRating, final Category category) {
```

2023-07-26 07:38 UTC, 70825 commented on backend/src/main/java/com/funeat/product/domain/Product.java
>          double calculatedRating = ((count - 1) * averageRating + rating) / count;
지금 발견했는데 코드 수정할 때 여기에도 final 추가해줄 수 있나요?

2023-07-26 07:38 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            상품_리뷰_추가_요청(new Review(member, product2, "review.png", 1L, "이 삼각김밥은 맛없다", false));
여기 부분들도 통일성 있게 복수_리뷰_추가_요청으로 수정하는건 어떤가요??

2023-07-26 07:38 UTC, 70825 commented on backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +        Member member = memberRepository.save(new Member("test", "image.png"));
```suggestion
        final Member member = memberRepository.save(new Member("test", "image.png"));
```

2023-07-26 08:17 UTC, 70825 commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    Page<ProductInCategoryDto> findAllByCategory(final @Param("category") Category category, final Pageable pageable);
```suggestion
    Page<ProductInCategoryDto> findAllByCategory(@Param("category") final Category category, final Pageable pageable);
```

아래 부분이랑 여기 수정해주세요~

2023-07-26 13:45 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/product/application/ProductService.java
> +        }
여기 분기 처리 나중에 리팩토링 해도 되지만, 생각났을 때 다른 부분 수정 사항 반영하면서 여기도 private 메서드로 분리하고 `pages`를 return하도록 수정하는 것도 좋아보여요!

2023-07-27 00:42 UTC, wugawuga approved these changes
다양한 방법을 시도한 것이 너무 존경스럽습니다!! 고생많으셨어요

2023-07-27 00:42 UTC, wugawuga commented on backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +        reviewRepository.save(new Review(member, product3, "review.png", 1L, "이 삼각김밥은 맛없다", false));
이 부분은 회의때 얘기했던 것처럼 나중에 다시 인수 조건들을 맞춘 후에 리팩터링 진행하면 좋을 것 같아요!!
👍

2023-07-27 03:29 UTC, Go-Jaecheol requested changes

2023-07-27 03:29 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/product/application/ProductService.java
> +            PageRequest pageRequest = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize());
```suggestion
            final PageRequest pageRequest = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize());
```

2023-07-27 03:33 UTC, 70825 approved these changes
고생하셨습니다 오잉~ 아래 부분 조금 더 수정할 부분이 있어서 확인해주세요~

2023-07-27 03:33 UTC, 70825 commented on backend/src/main/java/com/funeat/product/application/ProductService.java
>      private final CategoryRepository categoryRepository;
```suggestion
    private static final String REVIEW_COUNT = "reviewCount";
    
    private final CategoryRepository categoryRepository;
```

2023-07-27 03:33 UTC, 70825 commented on backend/src/test/java/com/funeat/product/persistence/ProductRepositoryTest.java
> +        reviewRepository.save(new Review(member, product3, "review.png", 1L, "이 삼각김밥은 맛없다", false));
여기도 reviewRepository.saveAll()로 바꾸는건 어떤가요??

2023-07-27 03:33 UTC, 70825 commented on backend/src/main/java/com/funeat/product/application/ProductService.java
> +            return productRepository.findAllByCategoryOrderByReviewCountDesc(category, pageRequest);
```suggestion
            final PageRequest pageRequest = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize());
```

2023-07-27 03:40 UTC, Go-Jaecheol approved these changes
고생했어용~~👍

2023-07-27 03:41 UTC, merged