[FE] feat: 로그인 페이지 구현
woowacourse-teams/2023-fun-eat pull request #162
Opened 2023-07-27 19:19 UTC by Leejin-Yang

## Issue

- close #157 

## ✨ 구현한 기능

- 로그인 페이지 마크업
- 로그인 페이지 경로 추가
- 로그인 API 요청 커스텀 훅 및 목 핸들러 작성

- ApiClient get 메서드의 반환값 수정
- 로고 크기 커스텀할 수 있도록 수정
- 카카오 아이콘 svg 추가

## 📢 논의하고 싶은 내용

- 로그인 요청은 응답 본문이 없어 ApiClient get 메서드의 반환값을 수정했습니다.. 타미의 이전 코드를 보고 본문의 유무에 따라 `fetchApi`의 반환값을 다르게 하려 했지만, 타입이 이리저리 꼬이더라구요 🥲 `useGet`이 받는 `callback`의 반환 타입인 `Promise<T>`를 기대하지만 `Response` 타입일 수도 있다는 타입스크립트의 빨간 메세지가 저를 피곤하게 합니다. 그렇다고 반환 타입을 `Promise<T | Response>`로 수정하면 `request` 함수 내부 `callback` 실행 후 set 하는 과정에서 타입이 안 맞으니까 그렇게 하지 말라고 하네요 ㅎㅎ.. 그래서 get 메서드의 반환값을 `response`로 수정했습니다. 의견 남겨주세요(제발)
- 로그인 페이지에서 헤더와 내비게이션바를 안 보이게 하기 위해 해당 페이지를 absolute로 두고 width, height를 100%로 두었습니다. 그래서 개발자도구에서 보면 헤더와 내비게이션바는 살아있습니다. 이 스타일은 상품 상세에도 적용해야 하는데 의견주세요!
- 페이지 디자인에 대해서 많은 의견 부탁드려요 😊
- 로그인 페이지로 어떻게 접근할 수 있을까요? 따로 접근할 수 있는 방법은 추가하지 않았습니다. 로그아웃된 상태라면 내비게이션바의 프로필을 눌렀을 때 이동하게 해야할까요?

<img width="906" alt="스크린샷 2023-07-28 오전 4 10 40" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/607f61d0-c2fa-40bc-8f56-820d0e6845a3">

## 🎸 기타

- 카카오 로그인 버튼을 누르면 프로필 페이지로 이동하게 목 핸들러 작성했습니다.

## ⏰ 일정

- 추정 시간 : 4시간
- 걸린 시간 : 5시간

2023-07-27 19:24 UTC, Leejin-Yang commented on frontend/src/hooks/auth/useLogin.ts
> +      const locationUrl = response.url;
```
const locationUrl = response.headers.get('Location');
```
응답 헤더의 Location에 url이 담아져 온다해서 위와 같이 작성했지만, null로 오더라구요.?

<img width="711" alt="스크린샷 2023-07-28 오전 4 22 52" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/6620e18b-0098-4dd7-b0b7-06489e8927e3">

콘솔 확인해보니 response.url로 와서 지금처럼 작성했습니다! 실제 응답에서도 저런식으로 올지는 모르겠습니다..

2023-07-28 01:21 UTC, xodms0309 commented on frontend/src/mocks/handlers/authHandlers.ts
> +    return res(ctx.status(302), ctx.set('Location', 'http://localhost:3000/profile'));
```suggestion
    return res(ctx.status(302), ctx.set({Location: 'http://localhost:3000/profile'}));
```
이렇게 해보시겠어요?

2023-07-28 08:20 UTC, xodms0309 requested changes
> 로그인 요청은 응답 본문이 없어 ApiClient get 메서드의 반환값을 수정했습니다.. 타미의 이전 코드를 보고 본문의 유무에 따라 fetchApi의 반환값을 다르게 하려 했지만, 타입이 이리저리 꼬이더라구요 🥲 useGet이 받는 callback의 반환 타입인 Promise<T>를 기대하지만 Response 타입일 수도 있다는 타입스크립트의 빨간 메세지가 저를 피곤하게 합니다. 그렇다고 반환 타입을 Promise<T | Response>로 수정하면 request 함수 내부 callback 실행 후 set 하는 과정에서 타입이 안 맞으니까 그렇게 하지 말라고 하네요 ㅎㅎ.. 그래서 get 메서드의 반환값을 response로 수정했습니다. 의견 남겨주세요(제발)

저는 황펭이 한 방법 괜찮은 것 같아요. 혹시 아까 공유해주신 부분 외에 고민점이 있으신가요?


> 로그인 페이지에서 헤더와 내비게이션바를 안 보이게 하기 위해 해당 페이지를 absolute로 두고 width, height를 100%로 두었습니다. 그래서 개발자도구에서 보면 헤더와 내비게이션바는 살아있습니다. 이 스타일은 상품 상세에도 적용해야 하는데 의견주세요!

스크린 리더에 읽히는게 약간 걸리네요.. react-router-dom에서 제공해주는 api가 따로 없을까요

> 페이지 디자인에 대해서 많은 의견 부탁드려요 😊

이 부분은 피그마에 남겼습니다!

> 로그인 페이지로 어떻게 접근할 수 있을까요? 따로 접근할 수 있는 방법은 추가하지 않았습니다. 로그아웃된 상태라면 내비게이션바의 프로필을 눌렀을 때 이동하게 해야할까요?

저희 서비스가 로그인을 하지 않아도 보는 것은 가능해서 황펭이 생각한 방법에 동의합니다~

2023-07-28 14:12 UTC, hae-on reviewed
> 로그인 요청은 응답 본문이 없어 ApiClient get 메서드의 반환값을 수정했습니다.. 타미의 이전 코드를 보고 본문의 유무에 따라 fetchApi의 반환값을 다르게 하려 했지만, 타입이 이리저리 꼬이더라구요 🥲 useGet이 받는 callback의 반환 타입인 Promise<T>를 기대하지만 Response 타입일 수도 있다는 타입스크립트의 빨간 메세지가 저를 피곤하게 합니다. 그렇다고 반환 타입을 Promise<T | Response>로 수정하면 request 함수 내부 callback 실행 후 set 하는 과정에서 타입이 안 맞으니까 그렇게 하지 말라고 하네요 ㅎㅎ.. 그래서 get 메서드의 반환값을 response로 수정했습니다. 의견 남겨주세요(제발)

저도 이 방법 좋습니다! 아까 이야기 나눴을 때 이해 완!

> 로그인 페이지에서 헤더와 내비게이션바를 안 보이게 하기 위해 해당 페이지를 absolute로 두고 width, height를 100%로 두었습니다. 그래서 개발자도구에서 보면 헤더와 내비게이션바는 살아있습니다. 이 스타일은 상품 상세에도 적용해야 하는데 의견주세요!

조건부로 로그인 화면일 때는 안 보이게 할 수 없나요?? (이런거 있는지 모름)
타미 말대로 스크린 리더에 걸리는 문제도 있을 수 있어요. 
물론 못 읽게 aria 설정을 주면 되긴 하는데 tab키 눌렀을 때도 안 잡힐지 그건 모르겠네용...

> 페이지 디자인에 대해서 많은 의견 부탁드려요 😊

저는 버튼 안에 글자가 bold 였으면 좋겠습니다~
보통 글자가 한 가운데 있는데 왼쪽에 있는거 신선하네요!

> 로그인 페이지로 어떻게 접근할 수 있을까요? 따로 접근할 수 있는 방법은 추가하지 않았습니다. 로그아웃된 상태라면 내비게이션바의 프로필을 눌렀을 때 이동하게 해야할까요?

넵 저는 내비게이션바 프로필 눌렀을 때 이동하는게 맞다고 생각합니다.

2023-07-28 14:12 UTC, hae-on commented on frontend/src/pages/LoginPage.tsx
> +  height: 54px;
customHeight으로 바로 button에 줄 수 있습니다~

2023-07-28 14:12 UTC, hae-on commented on frontend/src/pages/LoginPage.tsx
> +  background-color: #fee500;
얘도 바로 color로 button에 바로 줄 수 있어요~~

2023-07-29 12:07 UTC, Leejin-Yang commented on frontend/src/pages/LoginPage.tsx
> +        <Description>{DESCRIPTION}</Description>
빼먹었읍니다 😅

2023-07-29 12:08 UTC, Leejin-Yang commented on frontend/.storybook/preview-body.html
> +  <svg xmlns="http://www.w3.org/2000/svg">
해온 짱이네요!

2023-07-29 12:11 UTC, Leejin-Yang commented on frontend/src/pages/LoginPage.tsx
> +  background-color: #fee500;
color가 받을 수 있는 타입이 색상 키값이네요.!

2023-07-29 13:35 UTC, Leejin-Yang commented
@hae-on @xodms0309 

<img width="448" alt="스크린샷 2023-07-29 오후 10 33 44" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/179b46e6-cf63-493d-bfdf-abf2945cacdb">

리뷰 반영했습니다!

- 여러 레이아웃 파일을 만들었습니다.
- 우선 App에서 layout prop을 받아 조건문으로 처리 했습니다.

2023-07-30 04:05 UTC, hae-on approved these changes
잘 확인했습니다! 수고하셨어요~~👍

2023-07-30 04:05 UTC, hae-on commented on frontend/src/router/App.tsx
> +const App = ({ layout = 'default' }: AppProps) => {
app에서 props로 받아서 구현하셨군요! 좋네요! 근데 다른 또 헤더나 내비게이션 바가 없는 페이지가 생기면 auth처럼 추가하실 예정인가요? 아니면 그런 버전별로 나눌 생각이신가요??

2023-07-30 04:05 UTC, hae-on commented on frontend/src/pages/LoginPage.tsx
> +  background-color: #fee500;
아 맞네요.. 이 경우는 그냥 나둬야겠어요!

2023-07-30 05:38 UTC, xodms0309 commented on frontend/src/router/App.tsx
> +const App = ({ layout = 'default' }: AppProps) => {
그 상품 상세는 어떻게 하기로 했었죠?!

2023-07-30 11:38 UTC, Leejin-Yang commented on frontend/src/router/App.tsx
> +const App = ({ layout = 'default' }: AppProps) => {
상품 상세는 헤더만 있는 페이지라 다른 스타일이 될거 같네요...🥲
다음 이슈에서 처리해보겠습니다

2023-07-30 11:39 UTC, Leejin-Yang commented on frontend/src/router/App.tsx
> +const App = ({ layout = 'default' }: AppProps) => {
> app에서 props로 받아서 구현하셨군요! 좋네요! 근데 다른 또 헤더나 내비게이션 바가 없는 페이지가 생기면 auth처럼 추가하실 예정인가요? 아니면 그런 버전별로 나눌 생각이신가요??

지금처럼 if문으로 나누면 App의 코드가 많이 길어질거 같은데 이 부분 고민해봐야합니다..!

2023-07-30 12:02 UTC, xodms0309 approved these changes
확인했습니다~ 저 layout 분기문의 경우 생겼을 때 고민해봅시다~ 수고하셨어요 🐧

2023-07-30 12:05 UTC, merged