[BE] feat: 상품 랭킹 기능 추가
woowacourse-teams/2023-fun-eat pull request #204
Opened 2023-08-01 10:19 UTC by Go-Jaecheol

## Issue

- close #142 

## ✨ 구현한 기능

### 상품 랭킹을 조회하는 기능 구현

$$
  RankingScore = AvgRating - (AvgRating - 3.0)*2^{-log_{10}(Total Reviews + 1)}
$$

  - `1.0 ~ 5.0`의 AvgRating이 나오게 되므로 그 중간에 있는 `3.0`을 기준으로 기준치 선정
  - 평점이 `3.0` 보다 큰 상품에 대해서만 랭킹에 포함될 수 있도록 정책 변경

## 📢 논의하고 싶은 내용

- `ProductRepository`의 `findAllProductsAndReviewCountByAverageRatingGreaterThan3()` 메서드 명 이대로 괜찮은가..!
- `ProductService`에서 stream 한 번만 돌면서 각 Product의 랭킹 점수 구하고, 내림차순 정렬해서 상위 3개에 해당하는 dto 구하도록 했는데 괜찮나용
- `Product` 도메인에서 랭킹 점수를 구하는 비즈니스 로직을 처리하도록 하기 위해, `ProductReviewCountDto`에서 `Product` 엔티티를 필드로 가지도록 했는데 괜찮은지..!

## ⏰ 일정

- 추정 시간 : 2h
- 걸린 시간 : 4h

2023-08-01 15:35 UTC, 70825 requested changes
랭킹 기능 점수 계산하는거 최고 👍👍

2023-08-01 15:35 UTC, 70825 commented on backend/src/main/java/com/funeat/product/dto/RankingProductDto.java
> +    }
> Product 도메인에서 랭킹 점수를 구하는 비즈니스 로직을 처리하도록 하기 위해, ProductReviewCountDto에서 Product 엔티티를 필드로 가지도록 했는데 괜찮은지..!

저는 mapper 패키지를 따로 만들어서 관리하는게 아니면 그대로 두는게 좋아보여요~

2023-08-01 15:35 UTC, 70825 commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +                    "ORDER BY COUNT(r) DESC, p.id DESC ",
여기 부분도요!

2023-08-01 15:35 UTC, 70825 commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +                    "GROUP BY p ",
여기는 코드 포맷팅이 자동으로 되어서 그런 것 같은데, 되돌릴 수 있을까요?

2023-08-02 02:12 UTC, wugawuga commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    List<ProductReviewCountDto> findAllProductsAndReviewCountByAverageRatingGreaterThan3();
이미 반환값을 알고 있기때문에 findAllByAverageRatingGreaterThan3 도 괜찮아보여요!!

2023-08-02 02:21 UTC, hanueleee approved these changes

2023-08-02 02:21 UTC, hanueleee commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    List<ProductReviewCountDto> findAllProductsAndReviewCountByAverageRatingGreaterThan3();
>ProductRepository의 findAllProductsAndReviewCountByAverageRatingGreaterThan3() 메서드 명 이대로 괜찮은가..!

반환값 이미 알고 있으니까 위 메소드랑 비슷하게 `findAllByAverageRatingGreaterThan3` 좋을 것 같아요~~

2023-08-02 02:21 UTC, hanueleee commented on backend/src/test/java/com/funeat/product/domain/ProductTest.java
> +    void 평균_평점과_리뷰_수로_해당_상품의_랭킹_점수를_구할_수_있다() {
도메인 테스트 굿 👍

2023-08-02 02:21 UTC, hanueleee commented on backend/src/main/java/com/funeat/product/dto/ProductReviewCountDto.java
> +    private final Product product;
> Product 도메인에서 랭킹 점수를 구하는 비즈니스 로직을 처리하도록 하기 위해, ProductReviewCountDto에서 Product 엔티티를 필드로 가지도록 했는데 괜찮은지..!

비즈니스 로직에서 필요하기도 하고 해당 dto는 service안에서만 사용되니까 괜찮을 것 같아요!

2023-08-02 04:22 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/product/application/ProductService.java
> +                .collect(Collectors.toList());
Comparator만 따로 변수로 분리했습니다!

2023-08-02 04:27 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/product/persistence/ProductRepository.java
> +    List<ProductReviewCountDto> findAllProductsAndReviewCountByAverageRatingGreaterThan3();
저는 개인적으로 평점이 3.0보다 작은 상품들은 랭킹에 노출될 필요가 없다고 생각해요
이 부분은 서비스 정책에 관한 거라 다 같이 얘기해보죠!

2023-08-02 04:37 UTC, 70825 approved these changes
👍👍👍👍

2023-08-02 10:47 UTC, merged