[BE] refactor: 테스트 코드 리팩터링
woowacourse-teams/2023-fun-eat pull request #376
Opened 2023-08-09 15:26 UTC by 70825

## Issue

- close #343

## ✨ 구현한 기능

계산해보니 getter, dto를 제외하면 커버리지 100% 입니다 🥳 (PSA를 적용하여 테스트한 것 포함, 실제는 85%)

---

1. 🐛 `DatabaseCleaner` 테스트 격리를 제대로 하지 않음
**[발견]** : 일부 테스트에 있는 `...ignoringFields("id")`을 제거한 테스트에서 테스트 실패 발생
**[AS-IS]** : `DatabaseCleaner`가 각 테스트를 실행하기 전에 `id`값을 `1`로 초기화하지 않음
**[TO-BE]** : `DatabaseCleaner`가 데이터를 제거할 뿐만 아니라 `id`값도`1`로 초기화하도록 수정

---

2.  ✨`Fixture` 추가
이슈에서 언급했듯이 `public static final MEMBER = new Member(...)`처럼 만들면 테스트 격리가 되지 않습니다.
그래서 `return new Member(...)`로 생성 메서드를 만들어서 테스트 격리가 되도록 만들었습니다.

---

3. ✨ 다양한 경우의 성공 테스트, 누락된 성공 테스트 추가
8개의 성공 테스트를 추가했습니다.

---

5. 🔧 하나의 테스트에 2개 이상의 검증이 필요하면 `SoftAssertions` 사용
**[이유]** : 테스트를 실패할 때, 디버깅하기 편해집니다. `SoftAssertions`가 필요 없는 테스트들의 경우에는 통일성을 위해 적용했습니다.

---

6. 🔧 리포지토리 테스트, 서비스 테스트에`RepositoryTest`, `ServiceTest` 최상위 클래스 추가
**[이유 1]** : 컨텍스트 캐싱 재사용으로 인한 테스트 속도 증가
**[이유 2]** : 편한 관리를 위함

---

7. 🔧 `Repository`의 `save()`, `saveAll()` 관련 변경 사항
- [5-1] `save()`, `saveAll()` 메서드 네이밍 변경
  - **[이유]** : `save()`,`saveAll()`을 `@@_추가_요청`이라 하기엔 실제 메서드 행동과 다릅니다.
  - **[변경]** : `save()` → `단일_@@_저장`, `saveAll()` → `복수_@@_저장`으로 통일
- [5-2] `AcceptanceTest`, `ServiceTest`, `RepositoryTest`로 이동
  - **[이유]** : 수백줄이 넘는 코드가 `단일_@@_저장`, `복수_@@_저장`에 사용되고 있어서 중복 코드를 제거하기 위해 이동 했습니다.
- [5-3] `saveAll()` 메서드에 `varargs` 적용
  - **[이유]** : `복수_@@_저장(...)`을 하려면 `List.of(...)`로 감싸서 `복수_@@_저장(List.of(...))`를 해야 됐습니다. 그래서 메인 테스트 메서드에 `List.of(...)`를 만드는 코드가 100줄이 넘어갔습니다. 여기서 `varargs`를 적용하여 자식 테스트 메서드 내부에서 리스트를 감싸주어 메인 테스트의 가독성을 높이게 만들었습니다.

---

8.  🔧 `@Nested` 적용하여 테스트 계층화
**[적용 방법]** : `[메서드이름]_테스트` → `필요하면 세부 내용으로 계층화` → `성공_테스트`, `실패_테스트`로 적용했습니다.
**[장점]** : 테스트 가독성도 좋아지고, 유지보수하기 매우 편해집니다. 특히 누락된 케이스를 찾기 편해질 것으로 예상됩니다.
**[단점]** : `성공_테스트`, `실패_테스트`가 서로 섞여서 수행되지 않아 한 메서드에 대한 랜덤한 테스트를 수행하기 힘들어졌습니다.

---

9. 🔧 Mock 테스트 제거
기존에 카카오 로그인 부분을 테스트 할 수 없었는데, 생각해보니 `TestPlatformUserProvider`로 PSA를 적용해서 테스트 가능했습니다.
그래서 Mock 테스트를 제거하고, Classic 테스트로 변경했습니다.
이제 모든 테스트가 Classic 테스트입니다.

---

10. 🔧 `CategoryAcceptanceTest`, `ProductAcceptanceTest` 분리
- **[이유]** : 프로덕션 코드는 분리했는데, 테스트 코드는 분리가 안되어 있어서 분리했습니다.

---

12. 🔧 `Steps`에 있는 요청 메서드를 전부 컨트롤러 메서드 순서대로 수정
**[이유]** : 테스트 유지보수를 편하게 하기 위함

---

13. 🔧 그 외 테스트 코드 리팩터링
- 중복 메서드 제거, 가독성을 위해 자식 메서드 추가, 일부 자식 메서드에 `varargs` 적용

## 📢 논의하고 싶은 내용

테스트 삭제할만한 부분
- `통과하고_있다`라는 키워드로 만들었습니다. 억까 테스트가 좀 있을 수도 있어서 테스트 삭제할만한 부분은 리뷰로 알려주세요

프로덕션 코드 논의할 부분들
- `ReviewFavorite`의 `createReviewFavoriteByMemberAndReview`를 그냥 `create`로 바꿔도 될 것 같습니다.
  - 이유 : `ReviewFavorite`, `member`, `review`, `favorite`을 엔티티와 파라미터만 봐도 무슨 일을 하는지 충분히 추론 가능합니다.

## 🎸 기타

- 모든 테스트 코드를 수정했기 때문에 각자 리뷰 범위를 나눠서 진행하는게 좋아보입니다.

## ⏰ 일정

- 추정 시간 : 12
- 걸린 시간 : 36

2023-08-09 17:17 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
> +            void 신규_유저라면_마이페이지를_헤더에_담아_응답을_보낸다() {
```suggestion
            void 신규_유저라면_마이페이지_경로를_헤더에_담아_응답을_보낸다() {
```

2023-08-10 03:28 UTC, wugawuga reviewed
너무 고생하셨어요 👍

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/auth/AuthAcceptanceTest.java
>  @SuppressWarnings("NonAsciiCharacters")
@SuppressWarnings("NonAsciiCharacters")

이것도 추가하면 좋을 것 같아요!!

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
@SuppressWarnings("NonAsciiCharacters")
이 부분도요!

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +
이 공백 두줄은 의도하신걸까요?

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/product/CategoryAcceptanceTest.java
> +
이 부분도 공백 두줄!!

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            class 가격_기준_내림차순으로_카테고리별_상품_목록_조회 {
```suggestion
    @Nested
    class getAllProductsInCategory_성공_테스트 {

        @Nested
        class 가격_기준_내림차순으로_카테고리별_상품_목록_조회 {
```

이렇게 맨위 getAllProduct~~~ + 성공(실패) 테스트를 합치는 건 어떻게 생각하시나요?
ide 로 코드를 확인하는데 생각보다 뎁스가 깊어서 코드가 오른쪽으로 많이 밀려서요

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +                @Test
줄바꿈!

2023-08-10 03:28 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
@SuppressWarnings("NonAsciiCharacters")!!!

2023-08-10 03:38 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/product/ProductAcceptanceTest.java
> +            class 가격_기준_내림차순으로_카테고리별_상품_목록_조회 {
좋아요~~ 그거는 생각 못했는데 저렇게 수정하면 ide에서 코드 보기 더 수월해지겠네여

2023-08-10 09:29 UTC, hanueleee requested changes
너무너무 고생많으셨습니다 로건..........😭
짱짱맨

2023-08-10 09:29 UTC, hanueleee commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
>      }
RecipeServiceTest에서는
```java
    private MultipartFile 이미지_생성() {
        return new MockMultipartFile("image", "image.jpg", "image/jpeg", new byte[]{1, 2, 3});
    }
```
이던데 둘 중 하나로 통일하는건 어떨까요?

2023-08-10 09:29 UTC, hanueleee commented on backend/src/test/java/com/funeat/fixture/ProductFixture.java
> +    }
```java
    public static Review 리뷰_이미지test2_평점2점_재구매O_생성(final Member member, final Product product, final Long count) {
        return new Review(member, product, "test2", 2L, "test", true, count);
    }
```
ReviewFixture에서는 `평점2점`인데, ProductFixture에서는 `평점_2점`이어서
둘 중 하나로 통일하는건 어떨까요?

2023-08-10 09:29 UTC, hanueleee commented on backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
> +                });
```suggestion
                assertSoftly(softAssertions -> {
                    softAssertions.assertThat(actual1).isEqualTo(3);
                    softAssertions.assertThat(actual2).isEqualTo(1);
                });
```
이런식으로 테스트에 쓰이는 숫자는 그냥 그대로 사용하는건 어떨까요?!
변수로 빼면 해당 변수를 찾으러 코드를 거슬러 올라가야해서 then절의 가독성이 조금 떨어지는 것 같아서요..!

2023-08-10 09:29 UTC, hanueleee commented on backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
> +        class 성공_테스트 {
한 줄 공백!

2023-08-10 11:27 UTC, Go-Jaecheol reviewed
정말 힘든 작업... 고생했어요 😥
36시간의 사나이..

auth, member, product 위주로 확인했고, 몇 가지 코멘트 남겼습니다!
👍👍👍

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +                    softAssertions.assertThat(expected).containsExactly(actual.getMember());
```suggestion
                    softAssertions.assertThat(actual.isSignUp())
                        .isFalse();
                    softAssertions.assertThat(expected)
                        .containsExactly(actual.getMember());
```

전체적으로 `assertThat().~`도 점 하나 단위로 개행을 해서 가독성 높이는 건 어떻게 생각하시나요??

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +                // when, then
위키에 있는 백엔드 개발 문서에는 `when & then` 으로 표기한다고 되어 있어서
만약 여기만 `when, then`로 되어 있으면 수정해주시고,
전부 다 그렇다면 위키 문서를 수정해주세요!

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +            void 프로필_이미지_요청_값을_null로_설정하면_예외가_발생해야_하지만_통과하고_있다() {
이 2개는 저번에 얘기한 부분이네요.
나중에 까먹을 수 있으니까 TODO 달아두는 것도 좋아보여요!

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/member/domain/MemberTest.java
> +            void 사용자의_프로필_이미지_변경_값이_null이면_예외를_발생해야_하지만_통과하고_있다() {
여기도 TODO!

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/product/application/ProductServiceTest.java
> +                    final var expected = RankingProductsResponse.toResponse(List.of());
`Collections.emptyList()` 어떤가요?
빈 리스트라는 걸 명시해주는 장점도 있어서 좋아보여요

2023-08-10 11:27 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/product/application/ProductServiceTest.java
> +                    final var expected = RankingProductsResponse.toResponse(List.of());
만약 위에 emptyList 반영한다면 여기도..!

2023-08-10 11:31 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +            void 프로필_이미지_요청_값을_null로_설정하면_예외가_발생해야_하지만_통과하고_있다() {
이거 밑에 몇 개 더 있었는데 코멘트는 따로 더 안달았어요.
이 부분 우가가 예외 처리하면서 바로 수정할거면, 얘기만 잘 되면 굳이 _TODO_ 안달아도 될 것 같아용

만약에 나아아아아중에 처리할 거면 까먹을 수 있는 부분들만 달아주세요!

2023-08-10 13:01 UTC, 70825 commented on backend/src/test/java/com/funeat/fixture/ProductFixture.java
> +    }
`평점2점`으로 통일할게요!

2023-08-10 13:06 UTC, 70825 commented on backend/src/test/java/com/funeat/auth/application/AuthServiceTest.java
> +        }
네 맞아요! 요것도 삭제할지말지 이야기 해보면 좋을 것 같네여

2023-08-10 13:07 UTC, 70825 commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +                // when, then
아 맞다 👍👍

2023-08-10 13:12 UTC, 70825 commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
>      }
`ImageFixture`를 만들어서 저기에 추가했어요~

2023-08-10 13:13 UTC, 70825 commented on backend/src/test/java/com/funeat/auth/application/AuthServiceTest.java
> +        }
아니다 삭제할게요!

2023-08-10 13:38 UTC, 70825 commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +            void 프로필_이미지_요청_값을_null로_설정하면_예외가_발생해야_하지만_통과하고_있다() {
아마 서비스 테스트까지는 우가가 만들 것 같은데, 도메인쪽은 만약 안만든다면 우가 PR에서 언급하면 좋을 것 같아요~

2023-08-10 14:09 UTC, 70825 commented on backend/src/test/java/com/funeat/member/application/MemberServiceTest.java
> +                    softAssertions.assertThat(expected).containsExactly(actual.getMember());
잊고 있었던 객체지향 생활 체조 원칙 👍

2023-08-11 07:00 UTC, 70825 commented on backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
> +                });
전부 수정 완료

2023-08-11 07:01 UTC, Go-Jaecheol approved these changes
커밋 40개 미쳤다,,
정말 고생 많았어용

2023-08-11 09:05 UTC, hanueleee approved these changes
대 로 건 선 생 님

2023-08-11 09:05 UTC, wugawuga approved these changes
고생하셨슴다,,,, 로건

2023-08-11 09:06 UTC, merged