[FE] feat: ProductItem, ProductList 컴포넌트 추가
woowacourse-teams/2023-fun-eat pull request #43
Opened 2023-07-16 09:51 UTC by Leejin-Yang

## Issue

- close #26 

## ✨ 구현한 기능

- ProductItem 컴포넌트 추가
- ProductList 컴포넌트 추가
- image.d.ts 파일 추가

## 📢 논의하고 싶은 내용

- 목 데이터 만들면서 이미지 모듈을 못 읽어 image.d.ts 파일을 추가 했습니다. 추가하면서 tsconfig 설정(typeRoots)을 추가했는데 디자인 시스템에도 설정 추가(styled.d.ts)하면 아마 자동완성 할 수 있겠다는 생각이 듭니다.
- ProductItem 만들면서 ProductList도 만들었습니다.
- msw 쓰면 목 데이터는 mocks 폴더로 이동할 듯 합니다. 임의로 작성했습니다.

## 🎸 기타

|||
|--|--|
|![스크린샷 2023-07-16 오후 6 45 09](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/bec38b0c-8d54-486e-9582-58a0e1e301c1)|![스크린샷 2023-07-16 오후 6 45 18](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/92e66d2b-a214-48a5-9449-4810207017c7)|

2023-07-16 13:56 UTC, xodms0309 requested changes
황펭 수고 했어요~ 리뷰 몇 개 달아놨습니다
근데 typeRoots에 저거 추가하면 뭐가 바뀌나요??

2023-07-16 13:56 UTC, xodms0309 commented on frontend/src/components/Product/ProductItem/ProductItem.tsx
> +        <Text color={theme.textColors.info}>{price.toLocaleString('ko-KR')}원</Text>
시안을 보면 가격이 사이즈가 `xs` 여야 할 것 같아요

2023-07-16 13:56 UTC, xodms0309 commented on frontend/src/components/Product/mock.ts
> +import productImage from './mock_img.jpg';
아직 msw 안 했어도 이 파일은 mocks/data 아래에 있어도 될 것 같아요

2023-07-16 13:56 UTC, xodms0309 commented on frontend/src/components/Product/mock.ts
> +}
이 타입도 types아래에 product.ts 이런식으로 만들면 좋을 것 같아요

2023-07-16 13:56 UTC, xodms0309 commented on frontend/src/components/Product/ProductList/ProductList.stories.tsx
> +type Story = StoryObj<typeof ProductList>;
이거 통일에 대해서 얘기해봅시당

2023-07-17 08:41 UTC, hae-on approved these changes
따로 수정할 사항은 없습니다! 수고하셨어요~~

2023-07-17 12:37 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductItem/ProductItem.tsx
> +        <Text color={theme.textColors.info}>{price.toLocaleString('ko-KR')}원</Text>
xs 사이즈 너무 작아보여서 일단 뒀습니다..

2023-07-17 12:38 UTC, Leejin-Yang commented
@xodms0309 @hae-on 
여러가지 수정사항이 있었습니다.

- mocks로 목데이터 이동
- svg 적용

확인해주세요~

2023-07-17 14:29 UTC, xodms0309 approved these changes
많은 일이 있었던 그의 브랜치.. 수고하셨습니다~

2023-07-18 00:52 UTC, merged