[BE] feat: 사용자 마이페이지 리뷰 조회 기능 구현
woowacourse-teams/2023-fun-eat pull request #433
Opened 2023-08-13 07:33 UTC by wugawuga

## Issue

- close #418 

## ✨ 구현한 기능

- 사용자 마이페이지 접속 시 해당 사용자 리뷰 조회 기능 추가입니다.

## 📢 논의하고 싶은 내용

- x

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 2
- 걸린 시간 : 3

2023-08-13 07:40 UTC, 70825 reviewed
코드 깔끔하게 잘 작성했네요 👍
테스트 코드에서 수정할만한 부분 코멘트 남겼습니다~

2023-08-13 07:40 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +            복수_리뷰_저장(review1_1, review2_1, review2_2, review3_1, review3_2);
이거는 줄바꿈 안해도 될 것 같아요~

2023-08-13 07:40 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
actualReviews, expectedReviews를 검증하는건 `STATUS_CODE를_검증한다`, `페이지를_검증한다`처럼 따로 메서드로 분리하는건 어떤가요??

2023-08-13 07:40 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    LOGIN_MEMBER_NOT_FOUND.getMessage());
getCode(), getMessage()는 내부 메서드에서 처리하는게 핵심 테스트 로직 파악할 때 더 깔끔할 것 같은데 어떤가요??

2023-08-13 07:40 UTC, 70825 commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +            assertThat(result.getPage()).usingRecursiveComparison().isEqualTo(expectedPage);
> actualReviews, expectedReviews를 검증하는건 STATUS_CODE를_검증한다, 페이지를_검증한다처럼 따로 메서드로 분리하는건 어떤가요??

여기두요!

2023-08-13 12:11 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    LOGIN_MEMBER_NOT_FOUND.getMessage());
동의합니다!!

2023-08-13 12:12 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
따로 분리가 되어 있습니다. 하지만 emptyList 같은경우 List<Object> 로 메소드를 함께 쓸 수 없다는 단점이 있습니다.

2023-08-13 12:17 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
```java
private <T> void 사용자_꿀조합_목록_조회_결과를_검증한다(final ExtractableResponse<Response> response, final List<T> recipes, final PageDto page) {
    페이지를_검증한다(response, page);
    사용자_꿀조합_목록을_검증한다(response, recipes);
}

private <T> void 사용자_꿀조합_목록을_검증한다(final ExtractableResponse<Response> response, final List<T> expected) {

    final var actual = response.jsonPath().getList("recipes", MemberRecipeDto.class);

    assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
}
```

2023-08-13 12:17 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
이런식으로 구현하면 다같이 쓸 수 있습니다!! @70825 은 어떻게 생각하시나요?

2023-08-13 12:31 UTC, wugawuga commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +            assertThat(result.getPage()).usingRecursiveComparison().isEqualTo(expectedPage);
동의합니당!!!

2023-08-13 12:54 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
제네릭 메소드로 구현했습니다 ㅎㅎㅎ!!

2023-08-13 13:29 UTC, 70825 approved these changes
우가 최고 👍

2023-08-13 13:29 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
아 제가 못봤었네요 😭
`사용자_꿀조합_목록을_검증한다` 이 부분만 이렇게 바꿔도 될 것 같습니다!
T 사용하는건 생각도 못했녜요

2023-08-13 13:29 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    LOGIN_MEMBER_NOT_FOUND.getMessage());
저는 ErrorCode가 최상위 클래스인줄 알고 적었는데 서로 다른 것이었군요
그러면 우가 코드가 맞는 것 같습니다!

2023-08-14 05:00 UTC, Go-Jaecheol approved these changes
프로덕션 코드는 완벽한 것 같고, 저도 테스트 코드에서 개행 관련 코멘트 하나 남겼는데 그것만 확인해주세용 👍

2023-08-14 06:07 UTC, hanueleee requested changes
뚝딱뚝딱 우가

2023-08-14 06:07 UTC, hanueleee commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +                    .isEqualTo(expectedReviews);
제네릭 멋져요...👍

2023-08-14 06:52 UTC, wugawuga commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +            assertThat(result.getPage()).usingRecursiveComparison().isEqualTo(expectedPage);
동의합니다!!

2023-08-14 06:52 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberAcceptanceTest.java
> +    }
동의합니당!!

2023-08-14 06:53 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
> +    public ResponseEntity<MemberReviewsResponse> getMemberReview(final LoginInfo loginInfo, final Pageable pageable) {
interface 에서만 붙여서 깜빡했습니당!!!

2023-08-14 07:12 UTC, hanueleee approved these changes

2023-08-14 07:23 UTC, merged