[BE] feat: 사용자 마이페이지 꿀조합 조회 기능 구현
woowacourse-teams/2023-fun-eat pull request #435
Opened 2023-08-13 12:48 UTC by wugawuga

## Issue

- close #427 

## ✨ 구현한 기능

- 사용자 마이페이지 접속 시 해당 사용자 꿀조합 조회 기능 추가입니다.

## 📢 논의하고 싶은 내용

- x

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 2
- 걸린 시간 : 3

2023-08-13 13:57 UTC, 70825 reviewed
PageDto로 변경하면서 `ProductsInCategoryPageDto`도 `PageDto`로 변경하면 좋을 것 같아요~
프로덕션 코드는 깔끔해서 테스트 코드에만 수정할 부분이나 논의할 부분  코멘트 몇 개 남겼습니다!

2023-08-13 13:57 UTC, 70825 commented on backend/src/main/java/com/funeat/common/dto/PageDto.java
> +                   final Long requestPage, final Long requestSize) {
👍

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +        assertThat(result.getPage()).usingRecursiveComparison().isEqualTo(expectedPage);
softAssertions 추가하면 될 것 같습니다!

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
>      }
이거는 ImageFixture에 있는데, 리팩터링 PR에서 conflict 해결할 때 삭제를 못했었나봐요
이것도 삭제해줄 수 있나요?

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +                        return MemberRecipeDto.toDto(recipe, findRecipeImages, productsByRecipe);
```suggestion
                    .map(recipe -> {
                        final var findRecipeImages = recipeImageRepository.findByRecipe(recipe);
                        final var productsByRecipe = productRecipeRepository.findProductByRecipe(recipe);
                        return MemberRecipeDto.toDto(recipe, findRecipeImages, productsByRecipe);
```

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            final var recipe1_2 = new Recipe("test-title2", "test-content", member1);
이거는 RecipeFixture에 있는 `레시피_생성(member1)`로 사용해도 될 것 같은데 어떤가요?
그리고 member1, member2로 나눠서 각각 1개씩 저장하거나, 2개, 1개 저장해서 테스트하는게 더 확실하게 테스트할 수 있을 것 같습니다

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            final var result = recipeService.findRecipeByMember(member1.getId(), page);
result 대신 actual 어떤가요?

2023-08-13 13:57 UTC, 70825 commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            복수_멤버_저장(member1);
```suggestion
            단일_멤버_저장(member1);
```
이거 생각해보니까 굳이 단일, 복수 나눠서 사용하지 않고, saveAll()로 통일해서 `멤버_저장`으로 해도 될 것 같네요

2023-08-14 04:34 UTC, wugawuga commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            final var recipe1_2 = new Recipe("test-title2", "test-content", member1);
레시피_생성(member1)
레시피_생성(member1)

2023-08-14 04:50 UTC, wugawuga commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            복수_멤버_저장(member1);
이렇게 되면 모든 메소드를 다 수정해야될 것 같아서 이거는 수정사항에 달고 얘기해봐용!

2023-08-14 05:15 UTC, Go-Jaecheol reviewed
PageDto 수정에서 감동받았읍니다..
코멘트 하나 남겼는데 확인해주세요~

2023-08-14 05:15 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/common/dto/PageDto.java
> +        return new PageDto(
와 안그래도 `PageDto` 이거 얘기하려고 했는데,,,
우가우가 레전드레전드 👍

2023-08-14 05:15 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
> +                findRecipeImages.get(0).getImage(), recipe.getFavoriteCount(), productNames);
저희 꿀조합 작성할 때 사진 넣는 거 필수인가요??
아니라면 findRecipeImages에 빈 리스트 넘어올 수 있어서 `findRecipeImages.get(0).getImage()`에서 에러날 수 있을 것 같아요

2023-08-14 06:44 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
> +                findRecipeImages.get(0).getImage(), recipe.getFavoriteCount(), productNames);
필수로 알고 있습니다!!!
꿀조합 자체가 조합한 음식 자체를 뽐내는 기능이니까 사진을 받아야할 것 같아요 무조건!

2023-08-14 06:58 UTC, 70825 approved these changes
👍👍👍

2023-08-14 07:17 UTC, hanueleee requested changes
`PageDto` 보기만해도 속이 시원😎

2023-08-14 07:17 UTC, hanueleee commented on backend/src/main/java/com/funeat/member/presentation/MemberApiController.java
> +    }
통일성있게 LoginInfo에 `@AuthenticationPrincipal`, Pageable에 `@PageableDefault` 붙이면 좋을 것 같아용~~

2023-08-14 08:37 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/dto/MemberRecipeDto.java
> +                findRecipeImages.get(0).getImage(), recipe.getFavoriteCount(), productNames);
사진 선택이라고 해서 리팩터링 진행하였습니다!!

2023-08-14 08:54 UTC, merged