[BE] refactor: image url만 받게 수정
woowacourse-teams/2023-fun-eat pull request #568
Opened 2023-09-04 05:31 UTC by wugawuga

## Issue

- close #567 

## ✨ 구현한 기능

- 원래 이미지 업로드 하던 거 걷어냈습니다.

## 📢 논의하고 싶은 내용

- x

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 1
- 걸린 시간 : 0.5

2023-09-04 12:27 UTC, 70825 reviewed
build.gradle에 있는 이미지 관련 의존성들 전부 삭제해도 문제 없어보여요
레벨3 초반에 적용하려고 했던 restdocs + swagger도 다시 생각해볼 수 있을지도..??
머지되면 저도 AOP 로깅 적용하겠습니다~
우가 최고 👍👍

2023-09-04 12:27 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
>                  .extract();
여기에 있는 `.log().all()` 삭제해야 할 것 같아요~

2023-09-05 01:12 UTC, Go-Jaecheol approved these changes
많이 귀찮은 작업이었을텐데 고생하셨어요~~ 👍

2023-09-05 04:18 UTC, hanueleee requested changes
이미지 저장 로직 추출 고생하셨습니다아..🤣

2023-09-05 04:18 UTC, hanueleee commented on backend/src/main/java/com/funeat/member/dto/MemberRequest.java
> +    private final String image;
얘도 `@NotBlank` 있어야 할 것 같아요!

2023-09-05 04:18 UTC, hanueleee commented on backend/src/main/java/com/funeat/member/application/MemberService.java
>          }
요 로직은 없애도 될 것 같아용

2023-09-05 08:34 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +            request.getImages().forEach(it -> recipeImageRepository.save(new RecipeImage(it, savedRecipe)));
동의합니다!

2023-09-05 08:34 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
>                  .forEach(it -> productRecipeRepository.save(new ProductRecipe(it, savedRecipe)));
동의합니다!

2023-09-05 08:34 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/member/MemberSteps.java
>                  .extract();
오 감사함다!

2023-09-05 08:35 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/dto/MemberRequest.java
> +    private final String image;
이미지는 필수니까 추가하겠습니다!!!

2023-09-05 08:35 UTC, wugawuga commented on backend/src/main/java/com/funeat/member/application/MemberService.java
>          }
동의합니다!

2023-09-05 16:16 UTC, 70825 approved these changes

2023-09-06 01:07 UTC, hanueleee approved these changes

2023-09-08 04:33 UTC, merged