[BE] feat: 특정 상품에 대한 리뷰 조회 API 최적화
woowacourse-teams/2023-fun-eat pull request #607
Opened 2023-09-12 18:54 UTC by 70825

## Issue

- close #596

## ✨ 구현한 기능

- DTO Projection 사용했습니다.
- 포스트맨으로 확인해보면 요청을 보내고 응답을 받기까지 29.89초 걸리던게 0.175초로 개선했습니다 (리뷰 2500만개 기준)
  - MySQL에서는 최적화한 쿼리문이 0.019초가 나옵니다
- 쿼리문 50개 → 14개 날아갑니다 (유저 검증 1개, 상품 검증 1개, 페이지 1개, 리뷰 11개라 태그 11개 검색)
- Review 테이블에 인덱스 설정했어요 (product_id, favoriteCount DESC, id)
  - favoriteCount는 나중에 스케줄러 적용할 예정이라 데이터 INSERT, UPDATE 주기가 느려서 적용할 수 있을 것 같아요
  - 인덱스에 DESC 붙이는건 MySQL 8.0부터 생긴 기능인데, `Order By`에 맞게 DESC 적용하니까 성능이 좋아지더라구요

- 테스트 방법
  - `localhost:8080/api/login/login/1`로 로그인 쿠키를 획득
  - `localhost:8080/api/products/1/reviews?sort=favoriteCount,desc&page=412346`는 기존 페이징 방식
  - `localhost:8080/api/future/products/1/reviews?sort=favoriteCount,desc&lastReviewId=4123460`는 바뀐 페이징 방식

## 📢 논의하고 싶은 내용

- 무한 스크롤 사용하니까 불필요한 데이터는 싹 다 날리고, 최소한의 데이터만 보내주고 있어요. 
그래서 프론트와 이야기한 후에 코드를 수정해야합니다
- 그래서 테스트 코드도 아직 작성하지 않았습니다

## 🎸 기타

테코톡으로 공부하는 분은 아래 순서로 간단하게 정리하면서 들으면 이해하기 좋을 것 같고, 추가적으로 공부할 내용으로 커버링 인덱스 적용할만한 상황이라면 적용하면 좋을 것 같습니다.

- 테코톡 공부 순서
  - [안돌의 INDEX](https://youtu.be/NkZ6r6z2pBg?si=be_fj_V8W1N4XGfm)
  - [올라프의 Clustered vs Non-clustered Index](https://youtu.be/js4y5VDknfA?si=8OubUTWFS4-c2MxR)
  - [레베카의 인덱스](https://youtu.be/9ZXIoh9PtwY?si=CpCzxkoiVUZW3GQj)
  - [로이스의 Index](https://youtu.be/ywYdEls88Sw?si=eHRiSZOdSELDnEBc)
  - [찰리의 인덱싱](https://youtu.be/P5SZaTQnVCA?si=UiYEPELtHlHj44yQ)
  - [라라, 제로의 데이터베이스 인덱스](https://youtu.be/edpYzFgHbqs?si=iq3_gF34-rsQtmkD)
  - [매트, 토르의 MySQL 성능 최적화](https://youtu.be/nvnl9YgnON8?si=mW19CeC1NIg7b9Ql)

- 추가적으로 공부하면 좋은 내용
  - 커버링 인덱스

- 최적화하다가 만난 내용
  - Using Filesort
  - Using Temporary, Using Filesort
  - Using MRR

## ⏰ 일정

- 추정 시간 : 12
- 걸린 시간 : 24

2023-09-13 08:36 UTC, 70825 reviewed
`SortingReviewDtoFuture`에서 `List<String> tagNames`를 `List<TagDto> tags`로 바꾸기 (데이터 전부 사용함)

2023-09-14 08:12 UTC, 70825 commented
다음주에 황펭과 이야기하고 진행할 예정 (9/18 ~ )

2023-10-10 08:47 UTC, 70825 commented
### 회의 결과

JPA + Specification으로 동적 쿼리를 만들어 수정하기로 결정

2023-10-12 03:46 UTC, 70825 commented on backend/src/main/java/com/funeat/review/dto/SortingReviewDto.java
> +                Collections.emptyList(),
태그 추가하는 코드는 리팩터링하면서 추가할 예정이에요

2023-10-13 04:58 UTC, wugawuga reviewed
동적쿼리 구현 너무 멋집니다!!
코멘트 확인해주세요!!

2023-10-13 04:58 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/specification/SortSpec.java
> +public enum SortSpec {
ReviewSortSpec 으로 변경되면 좋을 것 같아요!

2023-10-13 04:58 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/specification/SortingReviewSpecification.java
> +            return criteriaBuilder.greaterThan(createdAtPath, lastReviewCreatedAt);
LocalDateTime 도 사용가능하게 SortSpec 에서 Function 을 사용하지말고,
커스텀 함수형 인터페이스를 만들어서 진행하면 될 것 같아요! (제네릭을 사용해서)

2023-10-13 09:16 UTC, hanueleee requested changes
동적쿼리 참 쉽지 않네요.....
고생하셨습니다!!

2023-10-14 09:24 UTC, Go-Jaecheol requested changes
동적 쿼리 어렵네요..

이 어려운 걸 해내셨군요 👍

코멘트 몇 개 달아두었습니다! 확인해주세요~~

2023-10-14 09:24 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/review/dto/SortingReviewDto.java
> +    private LocalDateTime createdAt;
final이 빠진 이유가 있을까요??

2023-10-14 09:24 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +    private static final int START = 0;
`TOP`이랑 `START` 의미가 비슷한 것 같은데 하나만 사용하도록 바꾸는 건 어떤가요??

2023-10-14 09:24 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/review/application/SortReviewService.java
> +        return sortingReviews;
```suggestion
        return addTagsToSortingReviews(sortingReviewsWithoutTags);
```
Inline으로 가져가도 될 것 같아요!

2023-10-14 09:24 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +    private final SortReviewService sortReviewService;
`SortReviewService`는 어디서 사용되고 있는 건가용..??

2023-10-14 13:16 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +    private final SortReviewService sortReviewService;
아 망고 근로 갔을 때, 현재 코드가 정렬 조건별로 메서드 3개씩 있는 코드랑 동적 쿼리랑 혼재하고 있는데, 동적 쿼리로 완전히 교체할 예정이라 금요일에 간단하게 코드리뷰 받고, 주말에 리팩터링하려고 헀어요

현재 코드는 `SortReviewService`를 완전히 대체해서 삭제할 예정이에여

2023-10-16 01:57 UTC, 70825 commented on backend/src/main/java/com/funeat/review/dto/SortingReviewDto.java
> +    private LocalDateTime createdAt;
동적쿼리 이전에 DTO Projection으로 인해 `List<TagDto> tags`에 저장된 값이 없어서 final을 안붙였는데, 지금은 문제 없어보여서 final로 수정했어요~ 👍

2023-10-16 02:03 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/SortReviewService.java
> +        return sortingReviews;
파일 삭제 했어요~

2023-10-16 02:31 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +                    .collect(Collectors.toList());
적용하니까 코드가 완전 깔끔해지네요 ㄷㄷㄷ 👍

2023-10-16 04:32 UTC, Go-Jaecheol approved these changes
고생하셨슴다~!!👍

2023-10-16 05:01 UTC, wugawuga approved these changes
dto 클래스에서 Boolean -> 기본형으로 바꾸면 될 것 같습니다!

> 제 pr 에 달렸던 코멘트인데 dto 클래스에 isXXXX 메시지 보단 getter 로 구현하고요!

2023-10-16 08:31 UTC, hanueleee approved these changes
기나긴 목록 조회 개선 여정..
고생하셨습니다~~

2023-10-16 08:53 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/SortingReviewService.java
> +                .orElseThrow(() -> new ReviewNotFoundException(REVIEW_NOT_FOUND, lastReviewId));
네 프론트에서 코드 변경점이 엄청 많아서 안하기로 했었어요

2023-10-16 08:55 UTC, merged