[FE] feat: 화면 전환 시 선택된 카테고리 유지 및 스크롤 유지
woowacourse-teams/2023-fun-eat pull request #621
Opened 2023-09-13 11:13 UTC by xodms0309

## Issue

- close #575 

## ✨ 구현한 기능

- 선택된 카테고리 유지
- 스크롤 위치 유지

## 📢 논의하고 싶은 내용

- 실제 개발서버에 올라가서 무한스크롤이랑 합쳐졌을 때 잘 작동할지는 아직... 모르겠읍니다 ^_^ 스크롤 이벤트 안주고 intersection observer을 활용해보고 싶었는데 안되네요..

## 🎸 기타

x

## ⏰ 일정

- 추정 시간 :
- 걸린 시간 : 3일

2023-09-13 16:32 UTC, Leejin-Yang requested changes
숙원 사업 카테고리 유지... 타미 고생했습니다!
몇 개 수정해 볼 만한 부분 코멘트로 남겼는데 확인해주세요
저는 그 때 잘 동작한거 봤으니.. 배포해도 잘 동작 무조건입니다 👍

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/contexts/CategoryContext.tsx
> +  };
빈 객체로 두고 카테고리마다 하나씩 저장해두는거군요 👍

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/hooks/common/useScrollRestoration.ts
> +const useScrollRestoration = (currentCategoryId: number) => {
이 훅은 main 엘리먼트를 찾는 대신 리스트 컨테이너에 ref를 걸어서 넘겨주어도 되지 않을까요..?
상태를 저장할 때 dom api로 직접 요소를 가져오는게 좋아보이진 않네요 🥲
같이 한 번 시도해봅시다.!

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/pages/ProductListPage.tsx
> +  }, [currentCategoryId]);
그럼 이 친구도 약간의 수정이 필요해보여요

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/pages/ProductListPage.tsx
> +  }
아래 훅들이 있어서 이 친구는 모든 훅 아래로 내려가야겠어요

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/pages/ProductListPage.tsx
> +        <div style={{ position: 'fixed', background: 'white', top: '60px', width: 'calc(100% - 40px)' }}>
오 타이틀과 정렬 버튼을 고정하는 친구인가요??
특별히 인라인으로 작성한 이유가 없다면 스타일드로 작성갑시다!

아 그리고 정렬버튼과 리스트 묶어준 이유가 에러나 로딩인 경우 정렬 버튼을 안 보이게 해서 정렬 상태 변경을 방지하기 위함인데 타미는 어떻게 생각하나요??

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/router/index.tsx
> +      </CategoryProvider>
상세 페이지에 접속해도 컨텍스트를 유지하기 위해 옮긴건가요?

2023-09-13 16:32 UTC, Leejin-Yang commented on frontend/src/hooks/context/useCategoryContext.ts
> +  return { categoryIds, selectCategory, currentTabScroll, saveCurrentTabScroll };
그대로 반환하니 구조 분해 하지 않아도 되겠네요!
그리고 다른 컨텍스트 훅처럼 예외처리도 있으면 더 좋아보여요.!

2023-09-14 01:34 UTC, xodms0309 commented on frontend/src/router/index.tsx
> +      </CategoryProvider>
네

2023-09-14 04:45 UTC, xodms0309 commented on frontend/src/contexts/CategoryContext.tsx
> +  };
네!

2023-09-14 04:45 UTC, xodms0309 commented on frontend/src/hooks/common/useScrollRestoration.ts
> +const useScrollRestoration = (currentCategoryId: number) => {
수정했읍니다. 짱짱

2023-09-14 04:46 UTC, xodms0309 commented on frontend/src/pages/ProductListPage.tsx
> +  }
근데 이렇게 되면 밑의 hook에서 저 `category` 값을 참조를 못하게 되는데 어떻게 할까요?

2023-09-14 05:14 UTC, xodms0309 commented on frontend/src/hooks/context/useCategoryContext.ts
> +  return { categoryIds, selectCategory, currentTabScroll, saveCurrentTabScroll };
수정했습니다! 다른 context와 동일하게 Value와 Action에 대해 나눴습니다

2023-09-14 06:54 UTC, hae-on approved these changes
타미 수고했읍니다
중간에 중괄호 빠진것만 넣어주세욤
롤백은 안돼~~

2023-09-14 06:54 UTC, hae-on commented on frontend/src/hooks/common/useScrollRestoration.ts
> +    if (!ref.current) return;
중괄호!

2023-09-14 06:54 UTC, hae-on commented on frontend/src/hooks/common/useScrollRestoration.ts
> +    if (!ref.current) return;
여기도 중괄호!

2023-09-14 06:59 UTC, xodms0309 commented on frontend/src/pages/ProductListPage.tsx
> +  }
[fe60442](https://github.com/woowacourse-teams/2023-fun-eat/pull/621/commits/fe604427c2a266190ffb545286726ae1d6377563)
아예 로직을 컴포넌트안으로 이동하는 것으로 바꿨습니다

2023-09-14 07:38 UTC, Leejin-Yang approved these changes
수고했어요 타미킴 👍

2023-09-14 07:47 UTC, merged