[BE] 특정 상품에서 좋아요를 가장 많이 받은 리뷰를 응답하는 API 연결
woowacourse-teams/2023-fun-eat pull request #724
Opened 2023-10-06 01:31 UTC by 70825

## Issue

- close #713 

## ✨ 구현한 기능

- 좋아요를 가장 많이 받은 리뷰를 응답하는 API
- 1) 데이터가 존재할 때 -> 정상 반환 (200)
- 2) 데이터가 존재하지 않을 때 -> 빈 응답을 반환 (200)

## 📢 논의하고 싶은 내용

- 데이터가 존재하지 않을 때 200이 맞을까요?

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 2
- 걸린 시간 : 2

2023-10-06 01:47 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +                .orElse(null);
여기 다들 확인점요~~

2023-10-06 04:54 UTC, hanueleee requested changes
> 데이터가 존재하지 않을 때 200이 맞을까요?

저는 괜찮다고 생각해요~~

2023-10-06 04:54 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/dto/MostFavoriteReviewResponse.java
> +    private Boolean favorite;
요 데이터는 넘기지 않아도 될 것 같아요~

2023-10-06 04:54 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/dto/MostFavoriteReviewResponse.java
> +    private Long favoriteCount;
`final` 붙이면 좋을 것 같아요!

2023-10-06 04:54 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +                .orElse(null);
메소드가 null을 반환하는게 좀 위험할 것 같기도한데,
요 상황에서는 이게 최선인 듯 하네요! (MostFavoriteReviewResponse.empty 이런거 하기도 애매..)
저는 null 동의!!

2023-10-06 04:54 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +        }
아까 로건이 확인하셨던 대로 이 로직이 없어도
response가 문제 없이 나가긴하는데,
명시적으로 표시해주는 것도 나쁘지 않을지도?!
어떻게 생각하시나여 다들

2023-10-06 04:58 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +                .orElse(null);
> 메소드가 null을 반환하는게 좀 위험할 것 같기도한데,
요 상황에서는 이게 최선인 듯 하네요! (MostFavoriteReviewResponse.empty 이런거 하기도 애매..)
저는 null 동의!!

원래 이걸로 해서 모든 필드값을 null로 보내는거였다가 타미랑 이야기해서 빈 응답을 반환하기로 했어요

2023-10-10 02:55 UTC, Go-Jaecheol reviewed
데이터가 없으면 204 No Content를 반환하는 건 어떻게 생각하나요?
라고 얘기하려고 했는데, 그러면 다른 API의 경우에도 일관성 있게 적용하고 프론트엔드랑도 얘기를 해야할 것 같네요..

다들 어떻게 생각하시나요??

2023-10-10 02:55 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
> +            // given && when
```suggestion
            // given & when
```

저희 컨벤션 요거인 거 같아용

2023-10-10 04:16 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
> +            // given && when
엇 이거 찾아보니까 제가 이전에 `&&`으로 쓴 게 몇 개 있어서 머지하기 전에 한 번에 다 수정해야겠네요

2023-10-10 04:25 UTC, 70825 commented on backend/src/test/java/com/funeat/review/persistence/ReviewRepositoryTest.java
> +    class findTopByProductOrderByFavoriteCountDescIdDesc_성공_테스트 {
141번 라인 테스트 이름이 잘못됐었군요
수정했어요!

2023-10-10 04:58 UTC, 70825 reviewed
[RFC 7231 - HTTP 1.1](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.5) 문서 확인해보니까 204로 사용하면 좋을 것 같아요

> The 204 (No Content) status code indicates that the server has
   successfully fulfilled the request and that there is no additional
   content to send in the response payload body.

> 204(No Content) 상태 코드는 서버가 성공적으로 요청을 수행했으며 응답 페이로드 본문에 보낼 추가 콘텐츠가 없음을 나타냅니다. 응답 헤더 필드의 메타데이터는 대상 리소스와 요청된 작업이 적용된 후 선택된 표현을 나타냅니다.

PUT, PATCH, DELETE에만 사용하는줄 알았는데, GET에도 사용할 수 있군요

---

참고로 200 응답은 빈 응답을 생성할 수 있긴한데, 데이터를 반환해야 할 때 204를 사용하는걸 권장하는 것 같네요

>    Aside from responses to CONNECT, a 200 response always has a payload, though an origin server MAY generate a payload body of zero length.
   If no payload is desired, an origin server ought to send 204 (No Content) instead.  For CONNECT, no payload is allowed because the successful result is a tunnel, which begins immediately after the 200 response header section.

> CONNECT에 대한 응답 외에도 200 응답에는 항상 페이로드가 있지만 오리진 서버는 0의 길이의 페이로드 바디를 생성할 수 있습니다.
페이로드를 원하지 않으면 오리진 서버에서 대신 204(No Content)를 전송해야 합니다. CONNECT의 경우 성공한 결과가 200 응답 헤더 섹션의 바로 뒤에 시작되는 터널이기 때문에 페이로드가 허용되지 않습니다.

2023-10-10 06:14 UTC, wugawuga approved these changes
고생하셨습니다 로건 !!!

2023-10-10 07:03 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +                .orElse(null);
Optional로 수정완

2023-10-10 07:37 UTC, hanueleee approved these changes
고생하셨습니다~~

2023-10-10 08:24 UTC, merged