[BE] feat: 리뷰 삭제 기능 구현
woowacourse-teams/2023-fun-eat pull request #735
Opened 2023-10-09 13:08 UTC by hanueleee

## Issue

- close #734 

## ✨ 구현한 기능

- 리뷰 삭제 api 구현

## 📢 논의하고 싶은 내용
1. updateProductImage 메소드 관련 ✅

기존 updateProductImage 메소드 질문 (리뷰 좋아요시 상품 이미지 업데이트)
- update 로직을 따로 빼서 controller에서 service 로직 두번 호출하는 이유?
- PageRequest 사용

우선 product를 파라미터로 받는 updateProductImage 메소드 추가해둔 상태
(기존 메소드는 reviewId를 파라미터로 받음)

2. S3 delete
```java
    @Transactional
    public void deleteReview(final Long reviewId, final Long memberId) {
        final Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new MemberNotFoundException(MEMBER_NOT_FOUND, memberId));
        final Review review = reviewRepository.findById(reviewId)
                .orElseThrow(() -> new ReviewNotFoundException(REVIEW_NOT_FOUND, reviewId));
        final Product product = review.getProduct();
        final String image = review.getImage();

        if (review.checkAuthor(member)) {
            deleteThingsRelatedToReview(reviewId, review);
            updateProductImage(product);
            imageUploader.delete(image);
        } else {
            throw new NotAuthorOfReviewException(NOT_AUTHOR_OF_REVIEW, memberId);
        }
    }
```
이런식으로
db에서 review 관련 데이터 지우기,
product의 대표 이미지 갱신,
s3에서 관련 이미지 삭제가
한 트랜잭션에서 이루어지고 있습니다.

s3 관련 로직을 다른 트랜잭션으로 분리해야할까요?

3. NotAuthorReviewException ✅

리뷰를 삭제하려는 사용자가 리뷰 작성자가 아닐 때 던지는 에러입니다.
info로 memberId만 넘겨도 될까요?

## 🎸 기타

- DB의 image컬럼에 값이 어떻게 들어가는지 보고(아마 cloudfront url이 들어가고 있는 것 같음) s3 delete 로직 조금 고칠 예정

## ⏰ 일정

- 추정 시간 : 2
- 걸린 시간 : 3

2023-10-10 06:17 UTC, wugawuga requested changes
연휴동안 고생하셨어요 오잉!
코멘트 확인해주세요

2023-10-10 06:17 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        reviewRepository.deleteById(reviewId);
이렇게하면 한 레코드당 delete 가 발생하지 않나요?

2023-10-10 06:17 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
도메인으로 넣는 것 좋습니다!! @70825 로건이랑 같이 얘기해보면 좋을 것 같아요

2023-10-10 06:17 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
그리고 .equals 가 아닌 비교연산자로 하신 이유가 궁금합니당

2023-10-10 06:17 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +                                                 @AuthenticationPrincipal final LoginInfo loginInfo) {
뭔가 정렬이 안된 것 같은데 올바른 정렬인가용?

2023-10-10 06:29 UTC, 70825 commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
오잉꺼로 통일했어요
그런데 member equals로 하게 되면 `equals, hashcode`를 재정의해야하지 않나요?
저는 `Objects.equals(this.member.getId(), member.getId());`로 했는데 이야기를 해봐야할 것 같아요

2023-10-10 06:52 UTC, 70825 requested changes
고생하셨어요 오잉 🥳
우가 코멘트랑 겹치지 않는 부분 코멘트 남겨서 확인해주세요~
#728 에서 여기에서 만든 메서드가 필요한데, 오잉의 코드 변경점이 많아서 오잉꺼 먼저 머지하고, 제꺼 PR 머지하는게 좋아보입니다!

2023-10-10 06:52 UTC, 70825 commented on backend/src/main/java/com/funeat/common/ImageUploader.java
> +    void delete(final String fileName);
```suggestion
    String upload(final MultipartFile image);

    void delete(final String fileName);
```

여기 줄바꿈 해야할 것 같아요

2023-10-10 06:52 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        }
```suggestion
        if (review.checkAuthor(member)) {
            deleteThingsRelatedToReview(reviewId, review);
            updateProductImage(product);
            imageUploader.delete(image);
            return;
        }
        throw new NotAuthorOfReviewException(NOT_AUTHOR_OF_REVIEW, memberId);
```

이렇게 수정하는건 어떤가요??

2023-10-10 06:52 UTC, 70825 commented on backend/src/main/java/com/funeat/review/exception/ReviewErrorCode.java
> +    NOT_AUTHOR_OF_REVIEW(HttpStatus.BAD_REQUEST, "리뷰의 작성자가 아닙니다.", "3002")
`해당 리뷰를 작성한 회원이 아닙니다.` 는 어떤가요?
`Member`쪽 에러 메시지를 보니까 회원으로 되어 있어서 이것도 회원으로 통일하는게 좋아보이더라구요

2023-10-10 06:52 UTC, 70825 commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +        return ResponseEntity.ok().build();
```suggestion
        return ResponseEntity.noContent().build();
```

이걸로 수정하면 더 좋아보여요

2023-10-10 06:52 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
> +    class deleteReview_실패_테스트 {
```
        final Member member = memberRepository.findById(memberId)
                .orElseThrow(() -> new MemberNotFoundException(MEMBER_NOT_FOUND, memberId));
        final Review review = reviewRepository.findById(reviewId)
                .orElseThrow(() -> new ReviewNotFoundException(REVIEW_NOT_FOUND, reviewId));
```

이 부분의 테스트도 추가해야 할 것 같아요~

2023-10-10 06:52 UTC, 70825 commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +    class deleteReview_실패_테스트 {
테스트를 더 추가해야 할 것 같아요~

[실패 테스트]
- 존재하지 않는 상품일 때
- 존재하지 않는 유저일 때

2023-10-10 06:52 UTC, 70825 commented on backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
> +            복수_리뷰_태그_저장(reviewTag1_1, reviewTag1_2, reviewTag2_1, reviewTag2_2, reviewTag2_3, reviewTag3_1);
해당 테스트는 태그 삭제가 메인인데, 많은 태그와 리뷰를 저장할 필요가 있을까요??
간단하게 태그는 1개만 저장하고, 리뷰 2개만 저장하면 1개의 리뷰가 삭제되어도 나머지 리뷰에 대한 태그 데이터는 그대로 남아있는지  테스트 할 수 있어보여요

2023-10-10 07:13 UTC, 70825 commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +        return ResponseEntity.ok().build();
@Go-Jaecheol @wugawuga 

https://github.com/woowacourse-teams/2023-fun-eat/pull/724#pullrequestreview-1666158638

여기보면 `No Content`로 수정해야할 것 같은데 어떤가요??

2023-10-10 08:06 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        }
우테코 스타일 오케이

2023-10-10 08:07 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/exception/ReviewErrorCode.java
> +    NOT_AUTHOR_OF_REVIEW(HttpStatus.BAD_REQUEST, "리뷰의 작성자가 아닙니다.", "3002")
네넵~~

2023-10-10 08:08 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +                                                 @AuthenticationPrincipal final LoginInfo loginInfo) {
ㅎㅎ 수정완료

2023-10-10 08:14 UTC, 70825 commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
이거 `Objects.equals(this.member.getId(), member.getId());`로 비교하면 도메인 단위 테스트를 추가할 때, id를 설정하는 곳이 없어서 테스트 검증이 불가능하네요

2023-10-10 14:01 UTC, hanueleee commented
(기존)
<img width="875" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91522259/7ebe37ae-8004-4bed-979e-510a7a6d6187">
review에 연관된 reviewTag조회
reviewTag 삭제 * N
review에 연관된 reviewFavorite조회
reviewFavorite 삭제 * M
review삭제
product의 가장 좋아요가 많은 review 조회
(+변경사항이 있다면 product 업데이트)
=  1 + N + 1 + M + 1 + 1 (+1)

(개선)
<img width="677" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91522259/bc893adc-1010-4cf4-ba77-2f9ce39c5a63">
review에 연관된 reviewTag조회
reviewTag 삭제
review에 연관된 reviewFavorite조회
reviewFavorite 삭제
review삭제
product의 가장 좋아요가 많은 review 조회
(+변경사항이 있다면 product 업데이트)
=  1 + 1 + 1 + 1 + 1 + 1 (+1)

참고 블로그 : https://aljjabaegi.tistory.com/681

2023-10-10 14:16 UTC, hanueleee commented on backend/src/test/java/com/funeat/review/application/ReviewServiceTest.java
> +    class deleteReview_실패_테스트 {
추가 완료~

2023-10-10 14:34 UTC, hanueleee commented on backend/src/test/java/com/funeat/acceptance/review/ReviewAcceptanceTest.java
> +    class deleteReview_실패_테스트 {
추가 완료~~😋

2023-10-11 00:35 UTC, wugawuga reviewed
<img width="905" alt="image" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/91244090/9a6303d2-49d9-4568-968a-a0bacf9aab73">

잉오가 올려준 블로그를 잘 보고 왔는데용!
사용한 메소드는 복합키가 연관이 되어있는 것으로 이해를 했는데요!
deleteBatch vs jpql 선택한 이유가 궁금합니당

2023-10-11 00:35 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
재정의를 안해도 됩니다. 먼지 Member 를 조회하고 나서 1차캐시에 영속화가 됩니다.
이후에 Review 에서 Member Id 로 지연 로딩을 하기 때문에 같은 아이디로 조회가 되어 1차 캐시를 바라보게 되어서 비교가 더 수월해질것 같기도 하네여.

근데 이 상황은 Id 로 모든 조회가 이루어져야 합니다.

2023-10-11 04:43 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/presentation/ReviewApiController.java
> +        return ResponseEntity.ok().build();
전체 회의 결과 : ok().build() 전부 204

2023-10-12 15:21 UTC, hanueleee commented on backend/src/test/java/com/funeat/review/persistence/ReviewTagRepositoryTest.java
> +            복수_리뷰_태그_저장(reviewTag1_1, reviewTag1_2, reviewTag2_1, reviewTag2_2, reviewTag2_3, reviewTag3_1);
그렇네용.. 수정했습니다!

2023-10-13 01:12 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/domain/Review.java
> +
equals 비교로 수정했습니다~

2023-10-13 02:29 UTC, hanueleee commented
> 사용한 메소드는 복합키가 연관이 되어있는 것으로 이해를 했는데요!
deleteBatch vs jpql 선택한 이유가 궁금합니당

`deleteAllByIdInBatch`는 복합키일 경우에는 `deleteAllInBatch`로 동작하고,
단일키일 경우에는 쿼리 한번 호출로 삭제할 수 있습니다. 
```
    delete 
    from
        review_tag 
    where
        id in (
            ? , ? , ?
        )
```
현재 reviewTag와 reviewFavorite은 다 단일키라 해당 메소드를 써도 괜찮다고 생각했습니다.
(+ deleteAllInBatch로도 해봤는데 
```
delete 
    from
        review_tag 
    where
        id=? 
        or id=? 
        or id=?
```
이렇게 나가더라구요??)

deleteAllByIdInBatch vs JPQL 중 deleteAllByIdInBatch를 사용한 이유는
이미 존재하는 메소드로 목표를 충족할 수 있다고 생각해서 굳이 새로운 jpql을 만들지 않았습니다!

2023-10-13 02:54 UTC, hanueleee commented
s3 이미지 삭제 로직에 스프링 이벤트 적용
- 리뷰 삭제가 가능할 때 (리뷰 작성자가 맞을 때) `ReviewDeleteEvent` 발행
- 리뷰 삭제 로직(reviewTag삭제, reviewFavorite삭제, review삭제)가 정상적으로 커밋되었을 때 이미지 삭제가 실행되어야 하기 때문에 `@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)`
- `@Async`를 사용해 비동기 처리 (+`@EnableAsync`)
  - Listener 로직이 실행되는 시간이 사용자의 응답을 느리게 만들지 않는다.
  - 별도로 `@Async`에 대한 설정이 없으면 새로운 비동기 작업을 스레드 풀에서 처리하는 게 아니라 새로운 스레드를 매번 생성해서 작업을 수행시키는 것이 디폴트 설정 -> application.yml에 스레드풀 설정 추가
- 테스트 관련
  - `@RecordApplicationEvents`와 `ApplicationEvents`로 이벤트가 몇번 발행됐는지 셀 수 있다
  - 비동기 테스트
    - 방법1) 비동기 로직이 끝날 때까지 대기
    - 방법2) 테스트 코드에서만 동기로 작동하게
    - => '비동기로 동작'하는 것을 검증하고 싶어서 방법1을 사용했습니다
 
기타
- 이미지 삭제 실패시 일단 로그만 찍어두었습니다. 추후에 이슈 따로 파서 보완할 예정 (db에 저장해두고 나중에 스케줄러로 삭제?)
- updateProductImage도 이벤트 처리하는거 어떨까 (productService의 역할이 아닐까)
- 이벤트 관련 클래스들 위치 어디에 둬야할까?

2023-10-13 05:00 UTC, 70825 approved these changes
`final` 키워드 안붙인게 좀 많아서 여기에만 대표적으로 코멘트 남길게요~

나머지는 코멘트는 빠르게 반영할 수 있을 것 같아서 approve 할게요

고생하셨어요~

2023-10-13 06:24 UTC, wugawuga reviewed
이벤트 도입이 처음이었는데, 너무 잘 구현해주신 것 같아요!!!
고생하셨어요 코멘트 한번 확인 부탁드려요

2023-10-13 06:24 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +    }
189번줄에서 찾은 review 를 통해 entity 를 넘겨주는 것이 괜찮아 보입니다
따로 아이디만 넘겨준 이유가 궁금합니다!

2023-10-13 06:49 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
> +                .cookie("FUNEAT", loginCookie)
@hanueleee 여기 JSESSIONID로 바꿔주세요 ([링크](https://github.com/woowacourse-teams/2023-fun-eat/pull/730#issue-1929600788))
이슈 따로 파서 테스트도 프로덕션이랑 쿠키 이름을 SESSION으로 통일할 예정이에요

2023-10-13 07:28 UTC, hanueleee commented on backend/src/test/java/com/funeat/acceptance/review/ReviewSteps.java
> +                .cookie("FUNEAT", loginCookie)
네넵!! JSESSIONID로 수정했습니다~

2023-10-13 07:33 UTC, hanueleee commented on backend/src/main/java/com/funeat/common/s3/S3Uploader.java
> +    private static final int BEGIN_INDEX = 31;
오오 그렇네요!!
해당 부분은
https://image.funeat.site/prod/5802E007-488E-4C05-90DA-910D3D6D0FCA.webp
에서
5802E007-488E-4C05-90DA-910D3D6D0FCA.webp만을 가져오는 기능이라

`BEGIN_FILE_NAME_INDEX_WITHOUT_FOLDER`라는 이름으로 수정하겠습니다! uuid 포함이라!

2023-10-13 07:36 UTC, 70825 commented on backend/src/main/java/com/funeat/common/s3/S3Uploader.java
> +    private static final int BEGIN_INDEX = 31;
UUID인줄 알았는데 다른거였군요 ㅋㅋㅋㅋ 좋아요 👍👍

2023-10-13 07:38 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
> +        if (image != null) {
오옹 Blank사용을 잊고 있었네요!
반영했습니다. 감사합니다!

2023-10-13 07:43 UTC, 70825 reviewed
코멘트 하나 더 남겼어요~
conflict 수정되면 다시 확인해보면 될 것 같아여

2023-10-13 07:43 UTC, 70825 commented on backend/src/main/java/com/funeat/common/s3/S3Uploader.java
> +            log.error("S3 이미지 삭제가 실패했습니다. 이미지 경로 : {}", image);
이거 아래 내용중에 하나로 변경하면 좋을 것 같아요
1. `S3 이미지 삭제에 실패했습니다. 이미지 경로 : {}`
2. `S3 이미지 삭제가 실패되었습니다. 이미지 경로 : {}`

2023-10-13 08:03 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +    }
앗 그러네요..
deleteById, deleteAllByIdInBatch 이런식으로 id 사용하는 부분이 많다보니까
무의식적으로 id를 넘긴것 같아요ㅜㅋㅋㅋ

reviewId말고 review를 넘기도록 수정했습니다!

2023-10-13 08:04 UTC, hanueleee commented on backend/src/main/java/com/funeat/common/s3/S3Uploader.java
> +            log.error("S3 이미지 삭제가 실패했습니다. 이미지 경로 : {}", image);
1번으로 수정했습니다. 감사합니다 ㅎㅎ

2023-10-13 08:53 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        reviewRepository.deleteById(review.getId());
deleteById 를 하면 findById 를 한번더 호출합니다!
이미 findById 로 찾아온 Review 를 사용하기 때문에 delete 가 더 괜찮아 보입니다!

2023-10-13 08:53 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        reviewRepository.deleteById(review.getId());
[링크](https://hwanchang.tistory.com/7) 한번 확인해 보시고 코멘트 달아주세용!

2023-10-13 08:54 UTC, wugawuga commented on backend/src/main/java/com/funeat/common/s3/S3Uploader.java
> +            log.error("S3 이미지 삭제에 실패했습니다. 이미지 경로 : {}", image);
👍

2023-10-13 09:03 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        reviewRepository.deleteById(review.getId());
헉 몰랐던 내용이네요. 감사합니다.
delete로 수정했습니다~

2023-10-14 10:25 UTC, Go-Jaecheol approved these changes
앞에서 리뷰 잘 해줘서 개행 관련 코멘트 하나 말고는 피드백 할 내용 없네요!
이벤트 적용하느라 고생하셨슴다~~~!

2023-10-14 10:25 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/common/EventTest.java
> +    }
```suggestion
    protected Long 단일_상품_저장(final Product product) {
        return productRepository.save(product).getId();
    }
    
    protected Long 단일_카테고리_저장(final Category category) {
        return categoryRepository.save(category).getId();
    }
    
    protected void 복수_태그_저장(final Tag... tagsToSave) {
        final var tags = List.of(tagsToSave);
        tagRepository.saveAll(tags);
    }
```
줄바꿈 필요할 듯요!

2023-10-15 07:41 UTC, hanueleee commented on backend/src/test/java/com/funeat/common/EventTest.java
> +    }
웁스 ㅎ
수정했습니다!

2023-10-16 03:14 UTC, wugawuga approved these changes
코멘트가 많았는데 열심히 고민하신 것 같습니다 ㅎㅎ
고생하셨어요

2023-10-16 04:34 UTC, merged