[BE] feat: 꿀조합 댓글 작성 기능 구현
woowacourse-teams/2023-fun-eat pull request #747
Opened 2023-10-12 05:18 UTC by wugawuga

## Issue

- close #745 

## ✨ 구현한 기능

- Comment  다대일 <-> 일대다 Recipe 양방향 매핑되어 있습니다
- Comment  다대일 -> Member 단방향 매핑되어 있습니다

Recipe 조회로 Comment 가 조회될 일이 많아서 양방향 매핑으로 구현했고,
Member 조회시 -> Comment 조회는 아직 예정에 없어서 단방향 매핑으로 구현했습니다!

## 📢 논의하고 싶은 내용

- x

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 3
- 걸린 시간 : 3

2023-10-13 06:36 UTC, 70825 requested changes
코드 완전 깔끔하네요.. 주말에 이거 보고 제꺼도 리팩터링 할게요~

2023-10-13 06:36 UTC, 70825 commented on backend/src/main/java/com/funeat/auth/application/AuthService.java
> +    private static final String COOKIE_NAME = "JSESSIONID";
여기 SESSION으로 롤백해야 할 것 같아요~

2023-10-13 06:36 UTC, 70825 commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +        final Specification<Comment> spec = CommentSpecification.findAllByRecipe(findRecipe, condition.getLastId());
여기 부분 어드민 PR 코드 리뷰할 때, 변수명이 `specification`이었는데, 하나로 통일하는게 좋아보여요~ ([어드민 코드 링크](https://github.com/woowacourse-teams/2023-fun-eat/blob/develop/backend/src/main/java/com/funeat/admin/application/AdminService.java#L74))
나머지 PR은 다 Open된 상태라 변경된 내용에 따라서 수정하면 될 것 같고, 어드민이나 이쪽만 변경하면 충분해보여요

2023-10-13 06:36 UTC, 70825 commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +        }
for each대신 for loop로 한 이유가 있나요??

2023-10-13 06:36 UTC, 70825 commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +        if (findComments.size() < 11) {
여기 클래스에 있는 숫자들이나 문자들 상수로 해두는건 어떤가요?!
저도 지금 상수로 변경할지말지 고민이네요

2023-10-13 06:36 UTC, 70825 commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentResponse.java
> +    public String toString() {
이거 재정의한 이유가 `author`가 안필요해서 그런건가여?

2023-10-13 06:36 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +                    "댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다"
여기 이걸로 변경하는건 어떤가요?
```
"1" + "댓글입니다".repeat(40)
```

2023-10-13 06:36 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +            }
오 이렇게 하는거 명확하고 깔끔해서 좋네요 👍

2023-10-13 06:36 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +        System.out.println("prettify = " + prettify);
여기 삭제해야할 것 같아요~

2023-10-13 06:36 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
> +                .cookie("JSESSIONID", loginCookie)
여기 메서드 추가된 두 곳 전부 SESSION으로 바꿔야해여

2023-10-13 06:46 UTC, 70825 commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeSteps.java
> +                .cookie("JSESSIONID", loginCookie)
### 정정

`spring-session-jdbc` 기능을 꺼버려서 JSESSIONID 그대로 유지하는게 맞아요
그래서 이슈를 하나 파서 테스트도 SESSION으로 통일할 예정입니다~

2023-10-13 07:34 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +        }
오 좋아요! subList 사용하여 가독성 높이는 식으로 리팩터링 진행했습니다!

2023-10-13 07:34 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/application/RecipeService.java
> +        if (findComments.size() < 11) {
상수화 했습니다!

2023-10-13 07:35 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +        System.out.println("prettify = " + prettify);
테스트 하면서 삭제를 안했네용 ㅠㅠ

2023-10-13 07:36 UTC, wugawuga commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +                    "댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다댓글입니다"
대박 감사합니다!

2023-10-13 07:36 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentResponse.java
> +    public String toString() {
이것도 디버깅하면서 추가한 내용이라 삭제했습니다!

2023-10-13 08:31 UTC, 70825 approved these changes
LGTM~

2023-10-13 15:45 UTC, hanueleee requested changes
오우 댓글 작성 & 조회까지 순식간에 완성하셨군요!!
멋집니다 역시 우가👍 고생하셨어요오

그런데 service 테스트를 작성해야할 것 같습니다..ㅎㅎ

2023-10-13 15:45 UTC, hanueleee commented on backend/src/main/java/com/funeat/comment/specification/CommentSpecification.java
> +            return criteriaBuilder.lessThan(commentIdPath, commentId);
사용되는 순서대로
메소드 순서를 lessThan -> equalToRecipe로 하는건 어떨까용?

2023-10-13 15:45 UTC, hanueleee commented on backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
> +            @ModelAttribute final RecipeCommentCondition condition) {
```suggestion
            @AuthenticationPrincipal final LoginInfo loginInfo,
            @PathVariable final Long recipeId,
            @ModelAttribute final RecipeCommentCondition condition) {
```
얘도 정렬 이렇게 하는거 어떨까요!!

2023-10-13 15:45 UTC, hanueleee commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
> +    }
얘는 다른 dto들과 다르게 정팩메를 만들지 않은 이유가 있나요??

2023-10-13 15:45 UTC, hanueleee commented on backend/src/test/java/com/funeat/acceptance/recipe/RecipeAcceptanceTest.java
> +            final var 응답 = 레시피_댓글_작성_요청(댓글작성자_로그인_쿠키_획득, 작성된_꿀조합_아이디, 꿀조합_댓글);
위에 사용한 
```java
final var 꿀조합_작성_응답 = 레시피_작성_요청(로그인_쿠키_획득(멤버1), 여러개_사진_명세_요청(이미지1), 레시피추가요청_생성(상품));
```
처럼
```java
final var 응답 = 레시피_댓글_작성_요청(로그인_쿠키_획득(멤버2), 작성된_꿀조합_아이디, 꿀조합_댓글);
```
요렇게 작성하는건 어떨까요??

2023-10-13 15:58 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/presentation/RecipeApiController.java
> +            @ModelAttribute final RecipeCommentCondition condition) {
이부분은 저희 컨벤션대로 wooteco.xml 로 설정한 거라서 그냥 가는게 좋을 것 같아요!

2023-10-14 09:03 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
> +    }
다른 가공이 필요없어서 생성자를 사용했습니다. 일관성있게 정팩메 사용으로 리팩터링했어용

2023-10-14 11:14 UTC, Go-Jaecheol reviewed
크게 수정할 부분은 없어보이네요!
역시 우가우가 👍

코멘트 두 개 남겨뒀는데 확인해주세요~

2023-10-14 11:14 UTC, Go-Jaecheol commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            final var product3 = new Product("스트링 치즈", 1500L, "image.png", "고소한 치즈", category);
```suggestion
            final var category = 카테고리_간편식사_생성();
            final var product1 = 상품_삼각김밥_가격1000원_평점2점_생성(category);
            final var product2 = 상품_삼각김밥_가격3000원_평점4점_생성(category);
            final var product3 = 상품_삼각김밥_가격2000원_평점3점_생성(category);
```
이거 다른 테스트들처럼 fixture 사용하는 거 어떤가요??
밑에 Request도!

2023-10-14 13:05 UTC, 70825 commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
> +    private final Boolean hasNext;
SortingReviewDto 리뷰 목록 API 성능 개선 PR 리팩터링하면서 같이 고쳐둘게요~

2023-10-15 08:04 UTC, hanueleee approved these changes
고생하셨습니다~~~

2023-10-16 03:15 UTC, wugawuga commented on backend/src/test/java/com/funeat/recipe/application/RecipeServiceTest.java
> +            final var product3 = new Product("스트링 치즈", 1500L, "image.png", "고소한 치즈", category);
좋습니다!! 감사합니다

2023-10-16 03:24 UTC, wugawuga commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
> +    private final Boolean hasNext;
getHasNext() 가 좋을 거 같습니다!!! dto 이기 때문에 객체에 질문을 던진다기보다 getter 를 통해 꺼내면 될 것 같아요

2023-10-16 04:33 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/recipe/dto/RecipeCommentsResponse.java
> +    private final Boolean hasNext;
그러면 ReviewDetailResponse도 저렇게 수정할게요 #758

2023-10-16 04:55 UTC, Go-Jaecheol approved these changes

2023-10-16 04:56 UTC, merged