[FE] feat: ReviewItem 컴포넌트 추가
woowacourse-teams/2023-fun-eat pull request #75
Opened 2023-07-18 17:15 UTC by Leejin-Yang

## Issue

- close #67 

## ✨ 구현한 기능

- ReviewItem 컴포넌트 추가

## 📢 논의하고 싶은 내용

- 별점을 1단위로 한다면 리뷰어의 평점은 별 다섯개 중에 색칠하는게 어떤지 제안해봅니다. (배민)
![IMG_6430](https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/c2aaa835-5615-4672-b5ae-d393ab2e0e7e)

- 좋아요를 누르지 않은 경우 하트 색깔을 일단 회색으로 했습니다. 라인만 있는 하트가 괜찮을까요? 그렇다면 지금 svg에서 어떻게 다뤄야 할까요?
- 그리고 리뷰를 올린 날짜가 필요할거 같습니다.

## 🎸 기타

- 리뷰 본문 더보기 제외 코드 먼저 올립니다. (두번째 사진은 개행이 들어간 리뷰입니다.)

<img width="468" alt="스크린샷 2023-07-19 오전 2 05 30" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/8f1d5bab-c4de-4357-bb61-4783d67ced85">
<img width="468" alt="스크린샷 2023-07-19 오전 2 05 43" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/a25a85db-c625-43cb-8e34-a3d217452e99">

## ⏰ 일정

- 추정 시간 : 2시간
- 걸린 시간 : 1시간

2023-07-19 01:24 UTC, xodms0309 commented
2줄 이상 넘어가면 말줄임을 적용하고 더보기 버튼을 눌렀을 때 해당 스타일을 제거하는 방식으로 하는게 어떠신가요?

2023-07-19 01:52 UTC, xodms0309 requested changes
수고하셨습니다 황펭~ 피그마에 lined-heart svg 만들어놨으니까 참고해주세요!
그리고 별점도 별로 표시하는 것 좋습니다.
리뷰 올린 날짜도 있으면 좋을 것 같네요

2023-07-19 01:52 UTC, xodms0309 commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +  const { userName, profileImage, image, rating, tags, content, rebuy, favoriteCount, favorite } = review;
`favorite` 보다는 `isFavorite`과 같이 boolean이라는 뜻이 담겨있으면 좋을 것 같아요

2023-07-19 01:52 UTC, xodms0309 commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +`;
어떤 요소는 styled로 만들고 어떤 요소는 `& > img` 이런식으로 하시는 이유가 궁금해요

2023-07-19 01:52 UTC, xodms0309 commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +const ReviewContentWrapper = styled.div``;
이건 비어있는 속성이라서 삭제해도 될 것 같아요

2023-07-19 01:56 UTC, xodms0309 commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +      <img src={image} height={150} alt={product} />
이 이미지는 리뷰한 사람이 올린 이미지 아닐까요? 그리고 `proudctName` 이 필요하다면 백엔드에게 필드에 `productName` 속성을 추가해달라고 요청하는 건 어떨까요?

2023-07-19 02:00 UTC, xodms0309 commented on frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
> +  ),
Rebuy가 없거나 Favorite이 아닌 경우도 스토리가 있으면 좋을 것 같아요

2023-07-19 03:49 UTC, Leejin-Yang commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +  const { userName, profileImage, image, rating, tags, content, rebuy, favoriteCount, favorite } = review;
백엔드와 이야기해보겠습니다!

2023-07-19 03:50 UTC, Leejin-Yang commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +`;
큰 스타일 변동이 아니라 스타일드 변수를 선언하는 것보다 컨테이너에서 적용하도록 했는데
따로 변수를 선언하는 것이 나을까요?

2023-07-19 03:50 UTC, Leejin-Yang commented on frontend/src/components/Review/ReviewItem/ReviewItem.tsx
> +      <img src={image} height={150} alt={product} />
해당 부분 불필요해 삭제했습니다!

2023-07-19 03:51 UTC, Leejin-Yang commented on frontend/src/components/Review/ReviewItem/ReviewItem.stories.tsx
> +  ),
타미가 말씀해주신 스토리는 Default로 작성했습니다.

2023-07-19 15:48 UTC, Leejin-Yang commented
@xodms0309 @hae-on 

||||
|--|--|--|
|<img width="385" alt="스크린샷 2023-07-20 오전 12 28 24" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/69216b3a-b459-4c35-8641-93d0ed82d7a2">|<img width="385" alt="스크린샷 2023-07-20 오전 12 28 15" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/b6b504ef-2a09-4ead-9072-dcbf41c13ed7">|<img width="385" alt="스크린샷 2023-07-20 오전 12 28 32" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/d3477c27-d798-4923-bd73-24d88ba39887">|

우선 별점 바꾸고 좋아요 버튼 크기 수정했습니다.
추가적으로 사진 없는 경우 처리했습니다.

문제가 몇가지 있는데요...

### 1

<img width="729" alt="스크린샷 2023-07-19 오후 11 46 28" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/78616893/310ecfab-af5f-4df7-a043-f60c5611f6cf">
위의 사진에서 좋아요 수의 Text 컴포넌트에서 Pretendard 폰트가 적용되지 않고 있습니다.

### 2

Button 컴포넌트에서 textColor의 prop 타입 수정이 필요해 보입니다.
타입은 ColorKeys를 받고 있는데 스타일은 key에 해당하는 value가 들어가는 것이 아닌 key 스트링이 그대로 들어갑니다.

### 3

리뷰 더보기 버튼의 경우 두 줄 이상인지 아닌지 판단하기 어렵더군요.. 모든 텍스트에 적용한다면 boolean 상태값으로 toggle 하면 될거 같은데(아님 체크박스로 한다던가) **두 줄 이상인지 판단**이 어렵습니다. 여러 블로그와 똑똑이에게 물어본 결과 

- 텍스트 길이의 기준값을 두고 기준값 이상 이하인지로 판단하기
  - 아래의 경우 반응형에서 문제가 있습니다.(작은 화면에서 두 줄이 넘지만, 화면이 커졌을 때 두 줄이 안 될 수 있다.)
- Text에 ref를 걸어 높이를 기준으로 판단하기
  - 현재 높이가 line-height * 2보다 큰지 판단합니다.
  - 아니면 ResizeObserve API를 사용한 커스텀 훅을 만들어 컨텐트를 관찰하던가 합니다.

우선 페이지 마크업 구현이 급하다 판단해 해당 부분은 뒤에 생각해보는게 어떤지 남깁니다...

### 4

그리고 리뷰 이미지가 여러개 일 때를 고려하지 않았는데 어떤 타입일지 이야기 해봐야 할 거 같습니다.

---

수정한 부분 확인 부탁드리고 코멘트 부탁드립니다. 감사합니다 🌞🐰

2023-07-20 04:09 UTC, xodms0309 approved these changes

2023-07-20 09:10 UTC, hae-on approved these changes

2023-07-20 11:21 UTC, merged