[BE] fix: ReviewDeleteEventListenerTest 통과하도록 수정
woowacourse-teams/2023-fun-eat pull request #778
Opened 2023-10-16 08:24 UTC by hanueleee

## Issue

- close #777 

## ✨ 구현한 기능

- 기존에 통과했다 실패했다 하던 ReviewDeleteEventListenerTest 를 통과하도록 고쳤습니다.

## 📢 논의하고 싶은 내용

- X

## 🎸 기타

- X

## ⏰ 일정

- 추정 시간 : 1
- 걸린 시간 : 1

2023-10-16 08:25 UTC, 70825 approved these changes

2023-10-16 08:34 UTC, 70825 requested changes
Approve 취소

2023-10-16 09:35 UTC, 70825 reviewed
머지하기전에 `@SuppressWarnings("NonAsciiCharacters")` 이거도 추가해주세요~

2023-10-16 12:10 UTC, hanueleee commented
실패하던 이유
- 요약 : 비동기로 동작하기 때문에 전 테스트에서 사용된 이벤트가 다음 테스트에서 잡힘
- 상세 : ""인 이미지를 가지는 event를 사용하는 테스트에서 자꾸 "test3" 이미지를 가지는 event가 잡힘 -> ""여서 작동하지 않아야 하는 delete 메소드가 "test3"을 읽고 작동 -> 실패

해결 : 테스트 이후 event 비워주기 `events.clear()`


![image](https://github.com/woowacourse-teams/2023-fun-eat/assets/91522259/4944df41-9a04-492b-8cb9-c1364074a0b2)

2023-10-16 13:01 UTC, 70825 requested changes
고생하셨어요 오잉~
테스트 코드 하나 물어볼거 있어서 코멘트 하나 남겼습니다~

2023-10-17 01:10 UTC, hanueleee commented on backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
>          }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그니까욬ㅋㅋ

2023-10-17 01:16 UTC, hanueleee commented on backend/src/test/java/com/funeat/common/EventTest.java
> +        return productRepository.save(product);
imageUploader 작동여부를 검증해야해서 모킹해둔 상태인데,
테스트 대상인 reviewService.delete뿐 아니라
reviewService.create에도 uploader가 사용되고 있어서 service까지 모킹했더니 작동이 이상하게 되더라구요..?
그래서 테스트 데이터를 service 메소드가 아닌 repository로 세팅해두기 위해 조금씩 바꿨습니다!

2023-10-17 01:22 UTC, 70825 commented on backend/src/test/java/com/funeat/common/EventTest.java
> +        return productRepository.save(product);
로컬단에서 이상하게 되나요? 저 Long으로 수정해서 돌리는데, 정상적으로 동작해서요

2023-10-17 01:42 UTC, hanueleee commented on backend/src/test/java/com/funeat/common/EventTest.java
> +        return productRepository.save(product);
아 저장 부분 말씀하시는거였군요 ㅎ
기존대로 Long을 반환하도록 수정했습니다!

2023-10-17 03:47 UTC, 70825 approved these changes

2023-10-17 08:25 UTC, wugawuga approved these changes
고생하셨어요 이벤트 테스트,,,,,👍

2023-10-17 08:25 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
>          }
hasText() 를 써도 될 것 같아요!

2023-10-17 08:59 UTC, hanueleee commented
hasText는 자바17에서 제공되는 기능이라 그대로 유지하는것으로 결정했습니다~~
(펀잇은 자바11 사용)

2023-10-17 13:09 UTC, Go-Jaecheol commented on backend/src/main/java/com/funeat/review/application/ReviewDeleteEventListener.java
>          }
헉ㅋㅋㅋㅋㅋ

2023-10-17 13:10 UTC, Go-Jaecheol approved these changes
버그 수정 좋아용 👍

2023-10-18 01:14 UTC, merged