[FE] feat: 상세 상품 리스트 페이지 타이틀 컴포넌트 추가 #55
woowacourse-teams/2023-fun-eat pull request #78
Opened 2023-07-19 03:35 UTC by hae-on

## Issue

- close #55

## ✨ 구현한 기능

- 상세 상품 페이지 타이틀을 구현하였습니다.
- product detail json과 type에 bookmark를 추가하였습니다.
- svg bookmark와 bookmarkFilled를 추가하였습니다.

## 📢 논의하고 싶은 내용

x

## 🎸 기타

x

## 📸 사진

<img width="887" alt="스크린샷 2023-07-19 오후 12 22 51" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/80464961/14f70e97-cc65-42ab-9308-b184e11fea31">
<img width="880" alt="스크린샷 2023-07-19 오후 12 23 02" src="https://github.com/woowacourse-teams/2023-fun-eat/assets/80464961/93b053e2-d86d-467c-9ae8-819d9d18684d">

2023-07-19 14:07 UTC, xodms0309 requested changes
해온 수고하셨습니다~ 리뷰 확인해주시고 ProductTitle도 index.ts에서 export 부탁드려용

2023-07-19 14:07 UTC, xodms0309 commented on frontend/src/components/Product/ProductTitle/ProductTitle.stories.tsx
> +export const Default: Story = {};
스토리에 북마크된 상태, 안된 상태가 둘 다 있으면 좋을 것 같아요

2023-07-19 14:15 UTC, Leejin-Yang reviewed
해온 수고했어요 🌞
코멘트 확인해주세요!

2023-07-19 14:15 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +        )}
```suggestion
          <SvgIcon variant={isBookmarked ? "bookmarkFilled" : "bookmark"} color={isBookMarked ? theme.colors.primary : theme.colors.gray5} />
```

컴포넌트 두 개보다 prop에 변화를 주는건 어떤가요?

2023-07-19 14:15 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +const ProductTitleWrapper = styled.div``;
스타일이 없어서 삭제해도 될 거 같습니다!

2023-07-19 14:15 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +const ProductTitleContainer = styled.h3`
디자인시스템의 Heading 컴포넌트를 쓰는건 어떤가요?
그리고 페이지의 타이틀이므로 h1이 더 적절해보여요!

2023-07-19 14:15 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +          `}
```suggestion
          css="margin-left: 10px;"
```

안에 변수를 사용하는 것이 없으니 중괄호 제거해도 됩니당

2023-07-19 14:15 UTC, Leejin-Yang commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +        <Button color="white" variant="filled">
아 뒤로 가기 버튼의 경우 타미의 Router PR에 Link 컴포넌트로 수정한거 있는데 그거 참고하면 됩니다 😊

2023-07-19 15:46 UTC, xodms0309 commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +        <Button color="white" variant="filled">
https://github.com/woowacourse-teams/2023-fun-eat/pull/82#discussion_r1267733716
요고 참고하면 될듯!

2023-07-20 04:05 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.stories.tsx
> +export const Default: Story = {};
props로 name과 bookmark를 받는 형식으로 수정하여 스토리북에서도 확인할 수 있도록 하였습니다!

2023-07-20 04:06 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +`;
title 컴포넌트도 같이 h태그로 받는 부분을 div로 바꾸고 text를 haeding으로 변경하였습니다!

2023-07-20 04:06 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +const ProductTitleWrapper = styled.div``;
내용을 추가하였습니다~~

2023-07-20 04:06 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +const ProductTitleWrapper = styled.div``;
내용을 추가하였습니다~~

2023-07-20 04:06 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +        )}
좋습니다~~ 수정 완!

2023-07-20 04:07 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +const ProductTitleContainer = styled.h3`
이 부분은 논의를 통해 div로 변경하는 것으로 결정되었습니다!

2023-07-20 04:07 UTC, hae-on commented on frontend/src/components/Product/ProductTitle/ProductTitle.tsx
> +        <Button color="white" variant="filled">
굿굿@@@

2023-07-20 04:10 UTC, xodms0309 approved these changes

2023-07-20 04:22 UTC, Leejin-Yang approved these changes
👩‍🎤

2023-07-20 04:32 UTC, merged