Feat/issue 84
woowacourse-teams/2023-fun-eat pull request #94
Opened 2023-07-20 04:35 UTC by wugawuga

## Issue

- close #84 

## ✨ 구현한 기능

- 리뷰 작성 시, 이미지 업로드는 필수가 아니어서 분기처리 추가
- 리뷰 작성 시, 카운트 쿼리를 통해 해당 상품의 리뷰 카운트를 가져와 평균 평점 계산 추가

## 📢 논의하고 싶은 내용

- x

## 🎸 기타

- x

## ⏰ 일정

- 추정 시간 : 6
- 걸린 시간 : 4

2023-07-20 05:53 UTC, 70825 requested changes

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/product/domain/Product.java
> +    private Double averageRating = 0.0;
상품에 아직 리뷰가 없을 때 기본값 0.0으로 해둔거 좋네요 👍

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/product/domain/Product.java
> +
```suggestion
    public void updateAverageRating(final Long rating, final Long count) {
        final double calculatedRating = ((count - 1) * averageRating + rating) / count;
        this.averageRating = Math.round(calculatedRating * 10.0) / 10.0;
    }
```

10.0도 상수로 해두는 것도 좋아보입니다~

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        }
이 부분은 나중에 리팩터링 할 수 있을 것 같아요~

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        productRepository.findById(productId)
likeReview 메서드 파라미터에 productId 자체가 필요 없어 보여요~
그러면 이것도 삭제할 수 있어 보입니다

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/product/domain/Product.java
> +
count = 0인 상황이 존재하지 않게 리뷰 먼저 등록하고, 평균 평점을 업데이트하는 것도 좋네요 👍

2023-07-20 05:53 UTC, 70825 commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        productRepository.findById(productId)
컨트롤러 코드를 확인했는데 `ReviewController`의 `toggleLikeReview` 메서드에 `@PathVariable Long productId`를 사용하지 않는 것도 좋아보입니다.

2023-07-25 01:06 UTC, wugawuga commented on backend/src/main/java/com/funeat/review/application/ReviewService.java
> +        productRepository.findById(productId)
리뷰가 존재한다면?

- 상품이 존재한다는 것이 당연히 이어지는 것 같아요!!

로건 말대로 없애도 무방할 것 같습니다!

2023-07-25 04:25 UTC, 70825 approved these changes
고생하셨어요 우가 🥳🥳🥳

2023-07-25 05:51 UTC, 70825 approved these changes

2023-07-25 07:02 UTC, Go-Jaecheol approved these changes
코드 설명 시간에 얘기한 부분 말고는 수정할 부분 없는 것 같아요.
수고하셨습니당~

2023-07-25 07:10 UTC, merged